### ISSUE TITLE
Doesn't always open the signature window, after signing it doesn't return to the application (Metamask android)

### ISSUE THREAD

**Issue by abasov90** [WalletConnect/WalletConnectUnity#108]
I manage to connect successfully and sign the message, but the signature window does not always open. And after signing, the return must be done manually. There are no such problems with the connection window. How can this behavior be improved?

Test wallet: Metamask android, unity 21.3.5 and WC I use the last one from the asset folder

```
        public async void Sign()
        {
            string msgParams = $"{MessageText} {wallet}";
            msgCache = HexStringUTF8ConvertorExtensions.ToHexUTF8(msgParams);
            var result = await PersonalSignAsync(msgCache);
        }
```

```
private async Task<string> PersonalSignAsync(string message)
        {
            var (session, address, chainId) = GetCurrentAddress();
            var request = new PersonalSign(msgCache, address);
            var result = await WC.Request<PersonalSign, string>(session.Topic, request, chainId);
            return result;
        }
```

**Comment by bulleador** [comment]
We're also having trouble making this stable. We had to completely drop trust wallet in our app due to this

**Comment by abasov90** [comment]
> We're also having trouble making this stable. We had to completely drop trust wallet in our app due to this

Were you able to make a return after signing?

**Comment by skibitsky** [comment]
Have you tried using deep links instead of universal links?

**Comment by abasov90** [comment]
> Have you tried using deep links instead of universal links?

I tried to reuse the link that is used for connection. On my device I was able to sign and return, on another, when I went to metamask, it immediately returned me back to the game or did not open the signature window. Perhaps you need to create a new link? I didn’t find functionality specifically for this in SDK

**Comment by skibitsky** [comment]
Did you configure `RedirectData`? I'm afraid that Unity sample is missing this part.

```csharp
WalletConnectUnity.ClientMetadata.Redirect = new RedirectData()
{                                                              
    Native = "my-dapp://"                                                          
};                                                             

SignClient = await WalletConnectSignClient.Init(new SignClientOptions()
{                                                                      
    BaseContext = WalletConnectUnity.BaseContext,                      
    Core = WalletConnectUnity.Core,                                    
    Metadata = WalletConnectUnity.ClientMetadata,                      
    Name = WalletConnectUnity.ProjectName,                             
    ProjectId = WalletConnectUnity.ProjectId,                          
    Storage = WalletConnectUnity.Core.Storage,                         
});                                                                    
```

You would need to modify `AndroidManifest.xml` in Unity to set up URL scheme: [Unity docs](https://docs.unity3d.com/Manual/deep-linking.html).

**Comment by abasov90** [comment]
> Did you configure `RedirectData`? I'm afraid that Unity sample is missing this part.
> 
> ```cs
> WalletConnectUnity.ClientMetadata.Redirect = new RedirectData()
> {                                                              
>     Native = "my-dapp://"                                                          
> };                                                             
> 
> SignClient = await WalletConnectSignClient.Init(new SignClientOptions()
> {                                                                      
>     BaseContext = WalletConnectUnity.BaseContext,                      
>     Core = WalletConnectUnity.Core,                                    
>     Metadata = WalletConnectUnity.ClientMetadata,                      
>     Name = WalletConnectUnity.ProjectName,                             
>     ProjectId = WalletConnectUnity.ProjectId,                          
>     Storage = WalletConnectUnity.Core.Storage,                         
> });                                                                    
> ```
> 
> You would need to modify `AndroidManifest.xml` in Unity to set up URL scheme: [Unity docs](https://docs.unity3d.com/Manual/deep-linking-android.html).

This code is present in the WCSignClient.InitSignClient method. But I did not configure AndroidManifest.xml

**Comment by skibitsky** [comment]
`WCSignClient.InitSignClient` doesn't include this part, you would need to add it manually.
```csharp
WalletConnectUnity.ClientMetadata.Redirect = new RedirectData()
{                                                              
    Native = "my-dapp://"                                                          
};                                                             
```

Alternatively, if you're using `WalletConnectUnity,` you can configure this directly from the Editor:
<img src="https://github.com/WalletConnect/WalletConnectUnity/assets/15127974/a80ed856-66a4-43a9-898f-4814cbff4076" width="500rem"/>


You need to set up url schema for your app in `AndroidManifest.xml.` and let `SignClient` know about it using the above code snippet or editor configuration.

This URL schema will be sent to the wallet along with the sign request. Once the user approves or rejects the request, the wallet will use this URL to automatically redirect the user back to the dapp.

If you don't specify a URL, some wallets might attempt to move themselves to the background, which can potentially activate your dapp again. However, this approach is unreliable, so I recommend setting up a URL scheme for your app.

**Comment by abasov90** [comment]
> `WCSignClient.InitSignClient` doesn't include this part, you would need to add it manually.
> 
> ```cs
> WalletConnectUnity.ClientMetadata.Redirect = new RedirectData()
> {                                                              
>     Native = "my-dapp://"                                                          
> };                                                             
> ```
> 
> Alternatively, if you're using `WalletConnectUnity,` you can configure this directly from the Editor: <img alt="" width="500rem" src="https://user-images.githubusercontent.com/15127974/275481944-a80ed856-66a4-43a9-898f-4814cbff4076.png">
> 
> You need to set up url schema for your app in `AndroidManifest.xml.` and let `SignClient` know about it using the above code snippet or editor configuration.
> 
> This URL schema will be sent to the wallet along with the sign request. Once the user approves or rejects the request, the wallet will use this URL to automatically redirect the user back to the dapp.
> 
> If you don't specify a URL, some wallets might attempt to move themselves to the background, which can potentially activate your dapp again. However, this approach is unreliable, so I recommend setting up a URL scheme for your app.

Thanks for your explanation. To consolidate the information and for those who will read this later:

Need to add:
`<intent-filter>
<action android:name="android.intent.action.VIEW" />
<category android:name="android.intent.category.DEFAULT" />
<category android:name="android.intent.category.BROWSABLE" />
<data android:scheme="unitydl" android:host="com.myapp.xapp" />
</intent-filter>`

and:

`WalletConnectUnity.ClientMetadata.Redirect = new RedirectData()
{                                                              
    Native = "com.myapp.xapp://"                                                          
};  `

Did I understand correctly?

**Comment by skibitsky** [comment]
Almost correct!

## Enable Deep Linking for Android
0. Navigate to `Edit > Project Settings > Player`.
1. In the **Android settings** tab, expand the **Publishing Settings** section.
2. In the **Build** section, enable **Custom Main Manifest**. This creates a new file called `AndroidManifest.xml` in `Assets/Plugins/Android`.
3. In the **Project** window, go to `Assets > Plugins > Android` and open the `AndroidManifest.xml` file.
4. Add the following code sample inside the `<activity>` element, and save the file.
```xml
<intent-filter>
  <action android:name="android.intent.action.VIEW" />
  <category android:name="android.intent.category.DEFAULT" />
  <category android:name="android.intent.category.BROWSABLE" />
  <data android:scheme="myapp" android:host="request" />
</intent-filter>
```
5. This will register your app as a handler of `myapp://request`URIs. Replace `myapp` with the name of your app. 

The `android:host` isn't necessary in our case, but recommended. Multiple apps could register to handle the same scheme. By specifying the host, you can ensure that only URIs matching both the scheme and the host are routed to your app.

## Configure Redirect in WalletConnect SDK
Configure `RedirectData` object in the `WalletConnectSignClient.Metadata`

```csharp
WalletConnectUnity.ClientMetadata.Redirect = new RedirectData()
{                                                              
    Native = "myapp://request"                                                          
};                                                             
```

Alternatively, you can configure this directly from the Editor:
<img src="https://github.com/WalletConnect/WalletConnectUnity/assets/15127974/a80ed856-66a4-43a9-898f-4814cbff4076" width="500rem"/>
