### ISSUE TITLE
"Send Transaction" button doesn't open the wallet, it opens web browser with "link.trustwallet.com" link.

### ISSUE THREAD

**Issue by agelessZeal** [WalletConnect/WalletConnectUnity#112]
At first, wallet connect was ok, but when I clicked the "send transaction" button, it didn't open the trust wallet that was connected wallet, it opened only the web browser with "[link.trustwallet.com](http://link.trustwallet.com/)" url.

**Comment by skibitsky** [comment]
This is a bug in Trust wallet. It happens with other WalletConnect SDKs as well, so it isn't related to Unity. The Trust team has been notified about the issue.

**Comment by abasov90** [comment]
I have a similar problem on iOS the deep link opens the browser instead of the signature window. It works correctly on anzhroid.
Unity version 2021.3.5f
Metamask iOS
@skibitsky
