### ISSUE TITLE
Different wallet interaction

### ISSUE THREAD

**Issue by agelessZeal** [WalletConnect/WalletConnectUnity#119]
I  connected the trust wallet. but when I click the send transaction button, it opens the  metamask wallet.
so I can't interact with my smart contract on the blockchain.

**Comment by skibitsky** [comment]
@agelessZeal can you please provide more information about your environment? The OS version, Unity version, etc.?

We have a Bug Report issue template with a list of all the information that could help us investigate the issue. I would appreciate if you could use it next time :)

**Comment by agelessZeal** [comment]
I have tested on Android platform.

**Comment by agelessZeal** [comment]
OS: Mac
Unity version: 2021.3.30
Test platform. Android
I connected the metamask android, then closed the app, and then connected the trust android again.
But this second wallet session returns the first metamask wallet address.

**Comment by skibitsky** [comment]
Did you call `SignClient.Disconnect(metamaskSessionTopic)` before connecting Trust?
How do you restore previous session after app restart?

**Comment by agelessZeal** [comment]
Yes, I did.   I have tested with the 2.1.6 merge again. But I have got the same error.
I connected the metamask android at first and signed out.
I connected the trust android again, but the account address in the ui shows the metamask 's address.
