### ISSUE TITLE
Issue Importing Walletconnect.Nethereum and Unity

### ISSUE THREAD

**Issue by Sterling-Malory-Archer** [WalletConnect/WalletConnectUnity#12]
I added Walletconnect.Nethereum folder to my Unity project.

I also imported all of the DLLs from https://github.com/Nethereum/Unity3dSimpleSampleNet461

But I keep getting this error and I don't know how to fix it:

```cs
Assets\WalletConnectUnity\WalletConnectSharp.NEthereum\WalletConnectNEthereumExtensions.cs(56,21): 
error CS0012: The type 'JsonSerializerSettings' is defined in an assembly that is not referenced. 
You must add a reference to assembly 'Newtonsoft.Json, Version=12.0.0.0, Culture=neutral, PublicKeyToken=30ad4fe6b2a6aeed'.
```

Any help in resolving this is kindly appreciated

**Comment by grandwiz** [comment]
Hi was this resolved?

**Comment by gigajuwels** [comment]
closed due to v1 depreciation
