### ISSUE TITLE
2.1.5 merge doesn't works on the android platform

### ISSUE THREAD

**Issue by agelessZeal** [WalletConnect/WalletConnectUnity#120]
When the connect button is clicked on the Android platform, there is an error in this code.

        public async void OnConnect()
        {
          
            if (WC.SignClient == null)
                await WC.InitSignClient();

**Comment by agelessZeal** [comment]
should I wait the 2.1.6 update now?

**Comment by skibitsky** [comment]
@agelessZeal Yes
