### ISSUE TITLE
Semaphore Disposal Prevents Signature Return On Subsequent Play Mode Runs

### ISSUE THREAD

**Issue by underclockeddev** [WalletConnect/WalletConnectUnity#121]
**Describe the bug**

```
ObjectDisposedException: The semaphore has been disposed.
System.Threading.SemaphoreSlim.CheckDispose () (at <1f66344f2f89470293d8b67d71308c07>:0)
System.Threading.SemaphoreSlim.WaitAsync (System.Int32 millisecondsTimeout, System.Threading.CancellationToken cancellationToken) (at <1f66344f2f89470293d8b67d71308c07>:0)
System.Threading.SemaphoreSlim.WaitAsync () (at <1f66344f2f89470293d8b67d71308c07>:0)
WalletConnectSharp.Storage.FileSystemStorage.Save () (at <e9b7caff5f764307b7b7f583346dfb90>:0)
WalletConnectSharp.Storage.FileSystemStorage.SetItem[T] (System.String key, T value) (at <e9b7caff5f764307b7b7f583346dfb90>:0)
WalletConnectSharp.Core.Controllers.JsonRpcHistory`2[T,TR].Persist () (at <e9c364cee32f4744828b182e35880014>:0)
WalletConnectSharp.Core.Controllers.JsonRpcHistory`2[T,TR].SaveRecordCallback (System.Object sender, WalletConnectSharp.Core.Models.History.JsonRpcRecord`2[T,R] event) (at <e9c364cee32f4744828b182e35880014>:0)
System.Runtime.CompilerServices.AsyncMethodBuilderCore+<>c.<ThrowAsync>b__7_0 (System.Object state) (at <1f66344f2f89470293d8b67d71308c07>:0)
UnityEngine.UnitySynchronizationContext+WorkRequest.Invoke () (at <4014a86cbefb4944b2b6c9211c8fd2fc>:0)
UnityEngine.UnitySynchronizationContext.Exec () (at <4014a86cbefb4944b2b6c9211c8fd2fc>:0)
UnityEngine.UnitySynchronizationContext.ExecuteTasks () (at <4014a86cbefb4944b2b6c9211c8fd2fc>:0)
```

**To Reproduce**
1. In the WalletConnectUnity component, change Project Name and Base Context to never-before-used values
2. Start a Unity Play Mode session
3. Scan QR code to connect mobile MetaMask to Unity
4. Request an eth_signedTypedData_v4 signature (approval in MetaMask not required, but if you do approve, this signature request actually succeeds. You can perform as many signature requests as you want in this initial play mode session)
5. End the Unity Play Mode session
6. Start a new Unity Play Mode session
7. (My WalletConnect is configured to automatically reconnect)
8. Request an eth_signedTypedData_v4 signature
9. Approve from MetaMask

**Actual behavior**
Above detailed semaphore exception is thrown at step 8, when the signature is requested
The method call `WalletConnectClient.Request` never completes
The signature is not sent to Unity

**Expected behavior**
Semaphore exception should not be thrown when signature is requested, eth_signedTypedData_v4 calls in subsequent play runs should return the signature to Unity.

**Environment**
- OS: Windows 11 Home, Version 10.0.22621 Build 22621
- Unity version 2021.3.18f1 Personal
- WalletConnectUnity version/commit: [ccb7c4b](https://github.com/WalletConnect/WalletConnectUnity/commit/ccb7c4bb8c15f1ce2e8efbb11059f2d8ff0dbbeb)

**Is this happening in Unity Editor or on a player like Android, iOS, Windows?**
Windows' Editor

**Wallets used for testing**
Metamask

**Additional context**
Due to both issues occurring on subsequent play mode runs, I assume this is related to https://github.com/WalletConnect/WalletConnectUnity/issues/114

I can perform eth_sendTransaction calls with success in subsequent play mode sessions. I only have the 2 (eth_sendTransaction and eth_signedTypedData_v4) implemented so they were all I could test so far

**Comment by skibitsky** [comment]
Hello @underclockeddev,

Thank you for opening this issue. A potential fix has been merged into WalletConnectUnity and included in the v3.0.2 release of the `core` package.
