### ISSUE TITLE
Wallet Connect Session Issue

### ISSUE THREAD

**Issue by agelessZeal** [WalletConnect/WalletConnectUnity#122]
At first, I connected the metamask, and after a successful metamask connection, I signed out.
And I have connected the trust wallet. but the connected wallet address is the metamask wallet address.
The second trust wallet connection should return the trust wallet address.

**Comment by skibitsky** [comment]
In the demo app address in the UI doesn't refresh immediately, but underlying session should be correct (i.e. sign request will go to the latest connected wallet).
