### ISSUE TITLE
Error in WCWebSocket.cs script when upgrading to version 2.1.6

### ISSUE THREAD

**Issue by yozdev** [WalletConnect/WalletConnectUnity#123]
**Describe the bug**
Hello @skibitsky.

I updated to v 2.1.6. After compilation, I get the following 3 errors in Unity Editor

Assets\WalletConnectUnity\Scripts\WalletConnectUnity\WCWebSocket.cs(197,22): error CS1501: No overload for method 'ListenOnce' takes 2 arguments

Assets\WalletConnectUnity\Scripts\WalletConnectUnity\WCWebSocket.cs(202,22): error CS1501: No overload for method 'ListenOnce' takes 2 arguments

Assets\WalletConnectUnity\Scripts\WalletConnectUnity\WCSignClient.cs(273,40): error CS1501: No overload for method 'ListenOnce' takes 2 arguments

**To Reproduce**
1. Update to v 2.1.6 in Assets
2. See error

**Environment**
 - OS: Windows 10
 - Unity version: 2022.3.10f1
 - WalletConnectUnity version/commit: 4f56711bdaf5cb07ab12b7c55c46507409dd65b0

**Is this happening in Unity Editor or on a player like Android, iOS, Windows?**
Unity Editor

**Comment by skibitsky** [comment]
Hello,

Did you also update WalletConnectUnity to the latest version?

**Comment by yozdev** [comment]
Hello @skibitsky 

I pulled the latest commit 4f56711bdaf5cb07ab12b7c55c46507409dd65b0

After that I copied the WalletConnectUnity folder in the following path WalletConnectUnity\Assets\WalletConnectUnity of my local repo

And added this folder in my Unity project's Assets

**Comment by skibitsky** [comment]
Thanks. Fixed in 00b7d4c5
