### ISSUE TITLE
Can't connect the wallet.

### ISSUE THREAD

**Issue by agelessZeal** [WalletConnect/WalletConnectUnity#124]
- WalletConnectUnity version/commit [13549d2f783ee3cb0b8d8f4a75f3cfe9e17aa62c]
I have tested it on Android.
When I click the wallet connect,
no change.
I got some error code in the Android Logcat.
![image](https://github.com/WalletConnect/WalletConnectUnity/assets/35507996/0c2c0d61-1582-4df5-8498-ba66e6f0ed37)

**Comment by skibitsky** [comment]
Please upgrade to v3 and reopen this issue if you still can't connect.
