### ISSUE TITLE
I can not import packages to my Unity Project

### ISSUE THREAD

**Issue by JamesW940516** [WalletConnect/WalletConnectUnity#125]
**Describe the bug**
When I import the described packages to my Unity project, there comes bugs and I can not import.
`[Package Manager Window] Error adding package: https://github.com/WalletConnect/WalletConnectUnity.git?path=Packages/com.walletconnect.ui.
Unable to add package [https://github.com/WalletConnect/WalletConnectUnity.git?path=Packages/com.walletconnect.ui]:
  No 'git' executable was found. Please install Git on your system then restart Unity and Unity Hub
UnityEditor.EditorApplication:Internal_CallUpdateFunctions ()
`

**To Reproduce**
Create new Unity Project.
Package Manager window / + / Add package from git url / https://github.com/WalletConnect/WalletConnectUnity.git?path=Packages/com.walletconnect.ui

**Expected behavior**
Should be imported without errors

**Screenshots**
![image](https://github.com/WalletConnect/WalletConnectUnity/assets/133299884/935d2caa-ab82-48c9-9518-17a51e702067)

**Environment**
 - OS: Windows 10
 - Unity version 2022.3.14f1[LTS]
 - WalletConnectUnity version/commit https://github.com/WalletConnect/WalletConnectUnity/commit/2ba67574b74026a9d978b1f618e711657653366f

**Is this happening in Unity Editor or on a player like Android, iOS, Windows?**
UnityEditor
**Wallets used for testing**
Metamask

**Additional context**

**Comment by skibitsky** [comment]
We should probably make it more explicit in the README. The errors happen because Unity can't automatically install git dependencies.

The dependency tree among packages in this repo is the following: Modal → UI → Core.

To install Core package, you don't need any dependencies.
To install UI package, you'd also need to manually install Core.
To install Modal package, you'd also need to manually install UI and Core.

Please let me know, if installing dependencies solves the error.

**Comment by JamesW940516** [comment]
![image](https://github.com/WalletConnect/WalletConnectUnity/assets/133299884/91e3b72e-02cd-4d31-ac42-8d4c4d6685c4)
![image](https://github.com/WalletConnect/WalletConnectUnity/assets/133299884/6b02d5b7-c3ec-4bd5-8ef4-a186d475f860)

Thank you for your advice.
I tried to import the CORE first.
Unfortunately the result was same
Please help me

**Comment by JamesW940516** [comment]
Thank you!
I could finally import all three packages successfully.
Could you please kindly indicated where I could find unity demo project of this library?

**Comment by skibitsky** [comment]
There is a sample for WalletConnectModal, which you can find [here](https://github.com/WalletConnect/WalletConnectUnity/tree/main/Packages/com.walletconnect.modal/Samples~/Modal%20Sample). To import the sample, update all packages.
