### ISSUE TITLE
Documentation for v3.0.0

### ISSUE THREAD

**Issue by justynspooner** [WalletConnect/WalletConnectUnity#126]
**Is your feature request related to a problem? Please describe.**
No idea how to use this in a Unity project. Tried dropping in the modal prefab but no idea how to open it.

**Describe the solution you'd like**
A demo and clear steps on how to use these packages

**Describe alternatives you've considered**
Reverse engineering the code

**Comment by justynspooner** [comment]
Am I right in saying that as it currently stands, the WalletConnectModal doesn't work on desktop? I just don't want to waste more time trying to get it working if it's still being built 😄

If that is the case, how am I meant to be using this package on desktop to display a QR code for the user to scan with their WalletConnect wallet app? Any points would be appreciate.

Many thanks

**Comment by skibitsky** [comment]
We now have a sample for WalletConnectModal, which you can find [here](https://github.com/WalletConnect/WalletConnectUnity/tree/main/Packages/com.walletconnect.modal/Samples~/Modal%20Sample). To import the sample, update all packages.

The Modal works on Windows, macOS, Android, and iOS. I'm still working on updating the documentation, but I hope that the sample code will be a helpful reference in the meantime.

**Comment by skibitsky** [comment]
WalletConnect Modal Unity docs have been added
https://docs.walletconnect.com/advanced/walletconnectmodal/about?platform=unity

**Comment by moosesnWoop** [comment]
Hi All, I would also like to see a working demo. i'm a self taught gamedev, so I understand how things interact and can read the code better if I see it all together. 

A demo with the modal would be great, so that we could see implementation in a working example, tinker around with it as well in PlayMode and then have the prefab to work off.

**Comment by skibitsky** [comment]
Updated docs for the [Sign](https://docs.walletconnect.com/api/sign/overview?platform=unity) and [Core](https://docs.walletconnect.com/api/core/pairing?platform=unity) APIs. Added URLs to [the README](https://github.com/WalletConnect/WalletConnectUnity?tab=readme-ov-file#documentation).
