### ISSUE TITLE
Unity demo project with WalletConnect

### ISSUE THREAD

**Issue by JamesW940516** [WalletConnect/WalletConnectUnity#127]
Hello! How are you?
First of all, thank you very much for your great work!
Your work enhances our life of blockchain and crypto.
I am a Unity NFT game founder and the lead developer.
I am currently working on a NFT game and using WalletConnect packages for the game.
There is a minor problem with the work.
I wish I had a unity demo project with WalletConnect.
If you have one, could you please kindly post the public git repo for your WalletConnect customers?
Unfortunately, I could not find any Unity related article or guide on Medium.
![image](https://github.com/WalletConnect/WalletConnectUnity/assets/133299884/56d0a991-cb90-4137-940c-b69bfa93a44d)
Anyway, thank you again for your innovative work.
Best Regards.
Thank you.
James.

**Comment by JamesW940516** [comment]
Is it possible to use WalletConnect for Unity Android app build and Android wallets?

**Comment by skibitsky** [comment]
@JamesW940516 

We now have a sample for WalletConnectModal, which you can find [here](https://github.com/WalletConnect/WalletConnectUnity/tree/main/Packages/com.walletconnect.modal/Samples~/Modal%20Sample). To import the sample, update all packages.

The Modal works on Windows, macOS, Android, and iOS.

**Comment by JamesW940516** [comment]
Thank you very much @skibitsky

**Comment by skibitsky** [comment]
Wallets will handle these cases automatically, you don't need to do anything. That said, MetaMask currently has some issues with chain switching, hopefully they will fix it soon.

To use WalletConnect on any platform you need to create a project at [WalletConnect Cloud](https://cloud.walletconnect.com), and use the ID of that project in Unity.

The Metadata section includes data that appears in a wallet when your app requests connection.

**Comment by JamesW940516** [comment]
Thank you very much for your clear explanation.

**Comment by JamesW940516** [comment]
Hello @skibitsky 
How are you?

I have a question
This project is for experimental purpose only?
Or ready to ship?

![image](https://github.com/WalletConnect/WalletConnectUnity/assets/133299884/c1f1fc8f-4937-448b-87b1-7231f0b68d4e)

Thank you

**Comment by skibitsky** [comment]
The Core package is stable enough for release. However, the Modal package may need a few more months to mature, so I wouldn’t recommend using it if you plan to release this month.

**Comment by JamesW940516** [comment]
Thank you very much @skibitsky 
I have some more questions

* https://github.com/WalletConnect/WalletConnectSharp is ready to ship?
* Could I use https://github.com/WalletConnect/WalletConnectSharp for Unity game project?
* Without the Modal package, could I still do walletconnection between unity mobile app and mobile wallet app?
* Could you please recommend the alternative other 3rd party library for WalletConnectUnity?

**Comment by skibitsky** [comment]
> https://github.com/WalletConnect/WalletConnectSharp is ready to ship?
Yes.

> Could I use https://github.com/WalletConnect/WalletConnectSharp for Unity game project?
Yes, but you would need to do additional work to make it compatible with IL2CPP. The WalletConnectUnity Core package is essentially a WalletConnectSharp that is compatible with IL2CPP and has additional features such as deep linking.

> Without using the Modal package, could I still do wallet connection between unity mobile app and mobile wallet app?
Of course! The purpose of the Modal package is to make it easier, but you can build your own UI with WalletConnectUnity Core package.

> Could you please recommend an alternative other 3rd party library for WalletConnectUnity?
Cannot recommend anything specific, but all third parties that I'm aware of are building on top of either WalletConnectSharp or WalletConnectUnity. By using our Modal or other packages, you get the latest improvements we make to the WalletConnect stack.

**Comment by JamesW940516** [comment]
Thank you very much for your help @skibitsky
