### ISSUE TITLE
WalletConnect with Trust Wallet

### ISSUE THREAD

**Issue by buihuuloc** [WalletConnect/WalletConnectUnity#13]
Hell there,

Is there any special setup for Trust Wallet?

**Comment by ecp4224** [comment]
PR #21 seems to be working with Trust Wallet. I will be testing on mobile as well but please let me know if this PR resolves your issue

**Comment by gigajuwels** [comment]
@buihuuloc, PR #21 has been merged into main, are you still experiencing this issue?

**Comment by gigajuwels** [comment]
Confirmed working on Mobile (android)
