### ISSUE TITLE
eth_SendTransaction doesn't open the wallet

### ISSUE THREAD

**Issue by agelessZeal** [WalletConnect/WalletConnectUnity#144]
android platform.
I have connected the trust wallet.
The send_signTransaction works well.
But the eth_sendTransaction button doesn't work.
It doesn't open the wallet.
But I open the trust wallet manually, there is the eth_sendTransaction ui popup to approve in the wallet.

**Comment by skibitsky** [comment]
@agelessZeal please open a new issue using the `Bug report` template.
