### ISSUE TITLE
Wallet connection doesn't work on iOS

### ISSUE THREAD

**Issue by armankarapetyandc** [WalletConnect/WalletConnectUnity#149]
I just imported this package by changing the ID and project name of the scriptable object after I used the example code to connect the wallet and build for ios, after running
Initialized the plugin but on the connect method they return an exception related to

---= XCode Logs =---
[JsonRpcProvider] Got payload {"id":1705345935540924,"jsonrpc":"2.0","error":{"code":-2146233088,"message":"Unable to find a constructor to use for type WalletConnectSharp.Network.Models.JsonRpcPayload. A class should either have a default constructor, one constructor with arguments or a constructor marked with the JsonConstructor attribute. Path 'method', line 1, position 10.","data":null}}

Closing websocket due to Close() being called

JsonSerializationException: Unable to find a constructor to use for type WalletConnectSharp.Network.Models.JsonRpcPayload. A class should either have a default constructor, one constructor with arguments or a constructor marked with the JsonConstructor attribute. Path 'id', line 1, position 6.
---= XCode Logs =---

**Environment**
 - OS: [macOS 13.4]
 - Unity version [2022.3.12f1]
 - iOS version: [16.5.1] 

**Is this happening in Unity Editor or on a player like Android, iOS, Windows?**
No

**Wallets used for testing**
 [e.g. Metamask iOS, Trust Android]
Trust Wallet

**Comment by skibitsky** [comment]
Hey @armankarapetyandc,

Have you tried setting `Managed Code Stripping Level` to `Minimal` in the `Player Settings`?

**Comment by armankarapetyandc** [comment]
Hi @skibitsky 

Yes, I noticed that this could be a problem, you are right, after changing the "Stripping Level" to "Minimal" everything works!

Thanks!
