### ISSUE TITLE
After pulling up the little fox and connecting, he didn't return to his own app

### ISSUE THREAD

**Issue by superdaidai** [WalletConnect/WalletConnectUnity#154]
**Describe the bug**
After pulling up the little fox and connecting, he didn't return to his own app

**Expected behavior**
The little fox should return to its own app after connecting, but so far it hasn't returned.
**Environment**
 - OS: [e.g. macOS 15.2]
 - Unity version [e.g. 2021.3.16f1]

**Is this happening in Unity Editor or on a player like iOS?**

**Wallets used for testing**
 [e.g. Metamask iOS, Trust IOS]

**Comment by skibitsky** [comment]
Hello @superdaidai, did you use iOS 17 for testing? In iOS 17+ wallets don't return to the dapp automatically.

**Comment by superdaidai** [comment]
Yes, will it be repaired in the future.

**Comment by skibitsky** [comment]
The fix should be implemented by the wallet providers. Unfortunately, dapps cannot take any action other than waiting until all wallets address this issue.

**Comment by superdaidai** [comment]
I understand. Thank you.
