### ISSUE TITLE
Unable to refresh QR code

### ISSUE THREAD

**Issue by superdaidai** [WalletConnect/WalletConnectUnity#155]
I use Wallet Connect in the United States. When I use it on my computer, Wallet Connect cannot refresh the QR code, while when I use it in other countries, the network connection to the US node can refresh the QR code. May I ask if there are any network requirements for this SDK?
![78f070fd3f450536369fac4f22de922](https://github.com/WalletConnect/WalletConnectUnity/assets/42162994/1a46ed8f-dbaa-49ea-8b7e-a7a94b046cb7)

**Comment by skibitsky** [comment]
It should work in the US. Any errors in the Unity Console or log files?

**Comment by superdaidai** [comment]
No logs, neither errors nor timeouts returned.

**Comment by skibitsky** [comment]
@superdaidai did this help?
https://github.com/WalletConnect/WalletConnectUnity/issues/156#issuecomment-1923274330

**Comment by superdaidai** [comment]
yes,very thank you.
