### ISSUE TITLE
Might be worth randomising the bridge server used at runtime

### ISSUE THREAD

**Issue by AlLansley** [WalletConnect/WalletConnectUnity#16]
Current bridge server of `https://f.bridge.walletconnect.org` can sometimes not work properly, likely due to load.

I read that servers a-z/A-Z/0-9 exist for the prefix so it might be worth picking a random one at startup to spread the load, as it can be confusing when things work, then don't, then do again etc. when there doesn't seem to be much rhyme or reason as to why things randomly decide to get flaky!

Just a thought!

**Comment by ecp4224** [comment]
The API already does this by default (even when you specify a `.walletconnect.org` bridge explicitly in the editor 😉)

However, the newest PR #21 now also randomizes the bridge URL again whenever a new session is created, so hopefully this will further improve the performance

You can see how the bridge randomization works [here](https://github.com/WalletConnect/WalletConnectUnity/blob/main/Assets/WalletConnectUnity/Scripts/WalletConnectSharp/WalletConnectSharp.Core/Network/DefaultBridge.cs#L62)

**Comment by AlLansley** [comment]
Cool - thanks for the update!
