### ISSUE TITLE
Inability to add multiple chains in RequiredNamespaces

### ISSUE THREAD

**Issue by dpradell-dev** [WalletConnect/WalletConnectUnity#168]
The title describes the issue for itself; check the *BUG* comment in the following example:

```
private ConnectOptions BuildConnectOptions()
    {
        var requiredNamespaces = new RequiredNamespaces();
        
        // TODO Make configurable
        var methods = new string[]
        {
            "eth_sendTransaction",
            "eth_signTransaction",
            "eth_sign",
            "personal_sign",
            "eth_signTypedData",
            "wallet_switchEthereumChain",
            "wallet_addEthereumChain"
        };

        var events = new string[]
        {
            "chainChanged", "accountsChanged"
        };
        
        requiredNamespaces.Add(Chain.EvmNamespace, new ProposedNamespace()
        {
            Chains = new []{"eip155:1", /*"eip155:5"*/}, //*BUG* Adding more chains cause OnConnectionError triggering.
            Events = events,
            Methods = methods
        });

        return new ConnectOptions
        {
            RequiredNamespaces = requiredNamespaces
        };
    }
```

**`WalletConnectModal.OnConnectionError`** event triggers when I scan the QR code (same happens in mobile devices).

I also tried selecting multiple chains in the [sample](https://github.com/WalletConnect/WalletConnectUnity/tree/main/Packages/com.walletconnect.modal/Samples~/Modal%20Sample#readme) and the same happens.

Same behaviour anyone? @skibitsky

Thanks in advance.

**Comment by skibitsky** [comment]
Hey @dpradell-dev,

Thanks for opening the issue. What wallet did you use for testing? MetaMask doesn't support multiple chains, but all other wallets should work just fine.

**Comment by skibitsky** [comment]
You have to manually change chains in MetaMask.

Firstly, use Optional Namespaces. This will make MetaMask to approve only one chain without.

Secondly, when you need to use another chain, call `wallet_addEthereumChain` and `wallet_switchEthereumChain` before making other requests.

I've made an [issue](https://github.com/WalletConnect/WalletConnectUnity/issues/169) for myself to add this functionality to the SDK.

### Resources
* How [Wagmi does chain switching](https://github.com/wevm/wagmi/blob/4ba761df16ceaa4746ccb0705ea8e514630b1c1b/packages/connectors/src/walletConnect.ts#L265-L288), you can rewrite this with C#
* [MetaMask documentation on `wallet_addEthereumChain`](https://docs.metamask.io/wallet/reference/wallet_addethereumchain/)
*  [MetaMask documentation on `wallet_switchEthereumChain`](https://docs.metamask.io/wallet/reference/wallet_switchEthereumChain/)

**Comment by dpradell-dev** [comment]
I already implemented `addEthereumChain` and `switchEthereumChain` manually. It’s working fine, but as explained before after switching to the new added chain the requests didn’t redirect to MetaMask automatically anymore.

Anyway, great to hear you’re adding this functionality. I’ll try this again when it’s added together with the Optional Namespaces tip.

Thanks, looking forward to this.

**Comment by dpradell-dev** [comment]
Hey @skibitsky,

Do you have an estimated date on when this will be implemented and live?

**Comment by skibitsky** [comment]
@dpradell-dev his week or the next
