### ISSUE TITLE
Session not recovering problems

### ISSUE THREAD

**Issue by songinnight** [WalletConnect/WalletConnectUnity#17]
There are two problems

- When I restart WalletConnect app I can't load previous session.
- Metamask onboard popup doesn't appears again when I cancel it or request permission again.

You can check the captured video here.

[![WallecConnect session problem](https://img.youtube.com/vi/PSNeeQvdJB4/0.jpg)](https://youtu.be/PSNeeQvdJB4 "WallecConnect session problem")

I guess carefully the async OnApplicationQuit/Pause codes doesn't work as expected.
and there should be detection of canceling permission.

[Environment]
Project: https://github.com/WalletConnect/WalletConnectUnity (2021.11.9)
Unity3D version: 2020.3.21f (Mono Build)
Nox emulator version: 7.0.1.7 (Android 7)

**Comment by ecp4224** [comment]
PR #21 has been opened that addresses several issues with session resuming/restarting/disconnecting. Please let me know if this PR resolves your issue, I will be testing as well before merging the PR

**Comment by songinnight** [comment]
> PR #21 has been opened that addresses several issues with session resuming/restarting/disconnecting. Please let me know if this PR resolves your issue, I will be testing as well before merging the PR

I've confirmed that the session resume issue has been resolved.
Thank you 👍

But cancel/disconnect issue still remains.

- Metamast onboard doesn't come up again after disconnect or canceled permission

[![Permission cancel issue](https://img.youtube.com/vi/6ouk8-NY60U/0.jpg)](https://youtu.be/6ouk8-NY60U "Permission Cancel")

[![Disconnect issue](https://img.youtube.com/vi/72gBtZw--1I/0.jpg)](https://youtu.be/72gBtZw--1I "Disconnect")

**Comment by ecp4224** [comment]
#21 has been merged to main and should address this issue
