### ISSUE TITLE
Deletion of the kotlin files.

### ISSUE THREAD

**Issue by crawfordbowl** [WalletConnect/WalletConnectUnity#170]
### **Is your feature request related to a problem? Please describe.**

This is not a bug directly caused by walletconnectunity. The problem happens when trying to merge other plugins. The issue raises when you try to use the old unity version, kotlin files and Firebase SDK.

Working setup:
Unity 2021.3.17 - WalletConnectUnity(has CanOpenUrl.kt) - No Problem. 
Unity 2021.3.17 - WalletConnectUnity(has CanOpenUrl.kt) - Firebase Unity SDK. No Jetifier.
Unity 2021.3.17 - WalletConnectUnity(has Linker.java) - Firebase Unity SDK. Use Jetifier.

Broken Setup:
Unity 2021.3.17 - WalletConnectUnity(has CanOpenUrl.kt) - Firebase Unity SDK. Use Jetifier.

### **Describe the solution you'd like**

Delete CanOpenUrl.kt and turn it into Linker.java. This way, you are not going to need to include Kotlin Library. It will be more compatible. There are no additional changes required in the SDK.

### **Describe alternatives you've considered**

I have tried to update 
-Firebase version 11.3(down) - 11.4 current - 11.5(up) - 11.6(up) - 11.7(up)
-2022.3.19 
-Disable Jetifier (cannot be done in the current project)

### **Additional context**

After twenty hours of building files and trying different Unity, Firebase, and Gradle Versions, I have given up... Thanks to the Android platform, billions of dependencies make you hate Android...

Firebase Issue: https://github.com/firebase/firebase-unity-sdk/issues/847

The changing versions started to cause more problems (https://github.com/firebase/firebase-unity-sdk/issues/945), so I gave up and just fixed the reason that caused it in the first place. I would like to add error texts here, but Android got me so mad I want to be done 👹

Here is the solution that can save someone 20 Hours 🗿 (https://github.com/crawfordbowl/WalletConnectUnity/commit/2fa938fd9f191c0c42837eae65a0336b0884769a)

**Comment by skibitsky** [comment]
@crawfordbowl thanks!

**Comment by tieugame2110** [comment]
Thanks @crawfordbowl, you saved me from stress, it took me 2 days for this issue.
