### ISSUE TITLE
Nothing happened After clicking and redirecting okx wallet in Android

### ISSUE THREAD

**Issue by Kheemta** [WalletConnect/WalletConnectUnity#176]
Nothing happened After clicking and redirecting okx wallet in Android
please give me  solution

**Comment by skibitsky** [comment]
Thanks @Kheemta, this will be fixed in the next release.

**Comment by Kheemta** [comment]
When update Next release ?

**Comment by skibitsky** [comment]
@Kheemta this week

**Comment by Kheemta** [comment]
I Need Help

i have connect wallet but issue is coming when i connect wallet in android
how to get wallet address in code which is connected wallet
private async void InitialiseDapp(bool connected)
{

        // SessionResumed is true if Modal resumed session from storage
        if (connected)
            EnableDappButtons();
        else
            EnableNetworksList();

        // Invoked after wallet connected
        WalletConnect.Instance.ActiveSessionChanged += (_, @struct) =>
        {
            Debug.Log(" "+ @struct.Topic);
            if ***@***.***))
                return;
            EnableDappButtons();
        };
        // Invoked after wallet disconnected
        WalletConnect.Instance.SessionDisconnected += (_, _) =>
        {
            Debug.Log($"[WalletConnectModalSample] Session deleted.");
            EnableNetworksList();
        };
    }

please check this give me sulation when i connect wallet public address
Debug
