### ISSUE TITLE
Sample not working after select chain and metamask

### ISSUE THREAD

**Issue by CoderMasonQin** [WalletConnect/WalletConnectUnity#181]
**Describe the bug**
fetch the sample project and run, select one chain and  click metamask, then get a blank dialog

**To Reproduce**
1. fetch latest code
2. Run the sample scene
3. select one of the chain
4. get a blank dialog 

**Expected behavior**
show 

**Screenshots**
![image](https://github.com/WalletConnect/WalletConnectUnity/assets/116541915/14a98074-2c3c-4640-b5d9-dcf6cb4b7bce)

**Environment**
 - OS: [e.g. Windows]
 - Unity version [e.g. 2021.3.22f1]
 - Package name and version [e.g. WalletConnectUnity Modal v1.1.0]

**Is this happening in Unity Editor or on a player like Windows**

**Wallets used for testing**
 [e.g. Metamask]

**Additional context**

**Comment by skibitsky** [comment]
Thanks @CoderMasonQin,

Did initial chain in MM match the one you selected from the list of chains in the game?

**Comment by skibitsky** [comment]
Did you update sample code after upgrading the package? Unity Package Manager doesn't update sample code automatically.

**Comment by CoderMasonQin** [comment]
Yeah, I am sure I have update the sample code.

**Comment by CoderMasonQin** [comment]
> Did you update sample code after upgrading the package? Unity Package Manager doesn't update sample code automatically.

Yeah, I have updated the code and the log keep print wait for connection to open

**Comment by skibitsky** [comment]
@CoderMasonQin can you access walletconnect.com on your network without VPN/proxy?

**Comment by CoderMasonQin** [comment]
> @CoderMasonQin can you access walletconnect.com on your network without VPN/proxy?

Seems I can't

**Comment by skibitsky** [comment]
Could you please change `Relay URL` in the `WalletConnectProjectConfig` scriptable asset to `wss://relay.walletconnect.org`?

**Comment by CoderMasonQin** [comment]
Wow, it works. Thx
