### ISSUE TITLE
I can't connect okx wallet

### ISSUE THREAD

**Issue by matthew2099** [WalletConnect/WalletConnectUnity#185]
**Describe the bug**
I can't connect the okx wallet.

**To Reproduce**
1. I import the Modal Sample
2. I fill in the projectID and other data
3. I build Andriod apk
4. I try to connect okx wallet
5. I can't connect that

**Expected behavior**
I think I can't receive response.

**Screenshots**
![화면 캡처 2024-03-25 133053](https://github.com/WalletConnect/WalletConnectUnity/assets/109068040/e5636543-d0d9-4ce3-bd6b-0f02b4c93dbc)
![화면 캡처 2024-03-25 133129](https://github.com/WalletConnect/WalletConnectUnity/assets/109068040/39f02a2b-d4ae-4b99-b3a2-39aaada58baf)

**Environment**
 - Unity version 2022.3.10f1
 - Package name and version : WalletConnectUnity Modal v1.1.1

**Is this happening in Unity Editor or on a player like Android, iOS, Windows?**
Window Android Player (NOX)

**Wallets used for testing**
okx wallet, android

**Comment by skibitsky** [comment]
Hey @matthew2099,

Which chain did you choose from the network list?

I have created a new build with `WalletConnectUnity Modal v1.1.1` and tested it with the OKX Wallet on an Android device. I did not experience the issue you mentioned. I tried both deep linking connection and QR code. Sometimes I'd get a network error in the wallet, but pressing the "Try again" button in the Modal always fixes it.

![WalletConnectUnity](https://github.com/WalletConnect/WalletConnectUnity/assets/15127974/d084db59-ddbe-4c71-9e7f-03620d051911)

**Comment by matthew2099** [comment]
I try to Ethereum Network.
and I see the picture too.
But When I click Connect wallet button, just i see Connecting picture.

**Comment by matthew2099** [comment]
And i try other Network
But i see the Connecting piturce too
![image](https://github.com/WalletConnect/WalletConnectUnity/assets/109068040/e75d01ed-b4b1-4be8-874c-2472bd731716)
![image](https://github.com/WalletConnect/WalletConnectUnity/assets/109068040/ab7272e9-fddf-491f-abd6-56b0a917a26a)

**Comment by matthew2099** [comment]
And just i think strange situation
if I waiting few minutes later, i click the cancel and the app is display connect.
Is there anything I missed?
![image](https://github.com/WalletConnect/WalletConnectUnity/assets/109068040/46ddf535-1d19-456f-bacd-d4a4cefd69f4)

**Comment by skibitsky** [comment]
I did more testing, and so far I can tell that sometimes it takes a long time for OKX to connect, but eventually it does connect. Do you run OKX in an emulator as well?

**Comment by matthew2099** [comment]
Yes my emulator and my phone have OKX wallet.
hum...i waiting for 10 minutes or more.
so do u mean the picture changes automatically??
Connecting picture to Connected picture?

**Comment by skibitsky** [comment]
The "Connecting" screen disappears, and OKX redirects back to the game, not the "Connected" screen. Sometimes, if you manually return to the game while the "Connecting" screen is still present in the OKX, the dapp buttons will appear in the game meaning that it was connected. It seems like OKX have some issues with their "Connecting" screen. Perhaps you should report it to them. I don't see any errors in the game logs either.

**Comment by matthew2099** [comment]
hum just i see only Connecting Picture.
just me too...i don't see log error
just this log repeate
![image](https://github.com/WalletConnect/WalletConnectUnity/assets/109068040/b359588f-b211-4813-858e-0d902210a0cd)

**Comment by skibitsky** [comment]
Hey @matthew2099,

I made some changes in the latest release that can improve the connection with OKX. Could you upgrade and try again, please?

**Comment by matthew2099** [comment]
@skibitsky 
Thank you.
I try that i was satisfied
But i think Metamask's connect is strange.
I think you need to check it.
