### ISSUE TITLE
Transaction failed：    WalletConnect Transaction Error: No matching key with tag: {tag}

### ISSUE THREAD

**Issue by Dejavu0709** [WalletConnect/WalletConnectUnity#186]
When I sent a call to smart  contract, the transaction sometimes return failed with error: 
WalletConnect Transaction Error: No matching key with tag: {tag}
![img_v3_029a_48a991a6-1148-41bb-957b-216977147a6h](https://github.com/WalletConnect/WalletConnectUnity/assets/71498147/c9a762ff-024a-4006-aaf0-1ad07dc889a0)

**Describe the bug**

**To Reproduce**
sometimes occure, sometimes success

**Expected behavior**

the transaction success 

**Environment**
 - OS: [Android]
 - Unity version [e.g. 2021.3.5f1]
 - Package name and version [e.g. WalletConnectUnity Modal v1.1.0]

**Is this happening in Unity Editor or on a player like Android, iOS, Windows?**
Android and Editor both
**Wallets used for testing**
Metamask

**Additional context**
Maybe because of the VPN?

**Comment by skibitsky** [comment]
Thank you, @Dejavu0709! I was able to reproduce the issue, and I will try to release a fix this week or next.

**Comment by Dejavu0709** [comment]
> Thank you, @Dejavu0709! I was able to reproduce the issue, and I will try to release a fix this week or next.

thanks my hero, expecting for your fix.

**Comment by skibitsky** [comment]
Fixed in WalletConnectUnity Modal v1.1.2
