### ISSUE TITLE
Landscape resolution: Wallet Connect QR code does not fit completely on the screen

### ISSUE THREAD

**Issue by NotNasty** [WalletConnect/WalletConnectUnity#191]
**Describe the bug**
Wallet Connect QR does not fit completely on the screen

**To Reproduce**
1) Open the mobile app in Landscape mode
3) Try "Connect Wallet" 
4) Click "All Wallets" button
5) Click on the "QR" icon
6) Check that QR fully fits on the screen

**Expected behavior**
Wallet Connect QR should fully fit on the screen

**Screenshots**
![image](https://github.com/WalletConnect/WalletConnectUnity/assets/46256092/2c982126-b09f-4c65-8588-6f8586d6d959)

**Environment**
 - OS: Android
 - Unity version 2021.3.23f1
 - WalletConnectUnity Modal v1.1.1

**Is this happening in Unity Editor or on a player like Android, iOS, Windows?**
Android

**Wallets used for testing**
Doesn't matter

**Additional context**
Thanks for the response in advance

**Comment by skibitsky** [comment]
Hello @NotNasty, thanks for opening the issue!

Did you test that on device? What device modal and Android OS version?

**Comment by NotNasty** [comment]
> Hello @NotNasty, thanks for opening the issue!
> 
> Did you test that on device? What device model and Android OS version?

Hi! I've tested it on phone Galaxy S20 FE (SM-G780F/DS), Android version 13

**Comment by skibitsky** [comment]
Thanks! The issue has been fixed in WalletConnectUnity Modal v1.1.2.

May I ask what project you are working on? I would love to learn more.
