### ISSUE TITLE
The screen with the "Coinbase Wallet" is empty

### ISSUE THREAD

**Issue by NotNasty** [WalletConnect/WalletConnectUnity#192]
**Describe the bug**
Coinbase Wallet screen is empty

**To Reproduce**
1) Try to Connect Wallet
2) Search "Coinbase Wallet"
3) Click "Coinbase Wallet" icon

**Expected behavior**
Coinbase Wallet screen should not be empty

**Screenshots**
![image](https://github.com/WalletConnect/WalletConnectUnity/assets/46256092/ab8e9df6-c771-459d-80ff-5372ef7f7950)
![image](https://github.com/WalletConnect/WalletConnectUnity/assets/46256092/0c7ad525-d105-4906-9310-36c02fb9496b)

**Environment**
 - Android
 - Unity version 2021.3.23f1
 - WalletConnect Unity Modal v1.1.1

**Is this happening in Unity Editor or on a player like Android, iOS, Windows?**
Both: Unity Editor & Android

**Wallets used for testing**
Coinbase

**Additional context**

> Exception: Wallet Coinbase Wallet has no available connection types.
> WalletConnectUnity.Modal.Views.ApprovalViewTabsController.Enable (WalletConnectUnity.Core.Networking.Wallet wallet) (at /Plugins/WalletConnect/com.walletconnect.modal/Runtime/Views/ApprovalView/ApprovalViewTabsController.cs:64)
> WalletConnectUnity.Modal.Views.ApprovalView.Show (WalletConnectUnity.UI.WCModal modal, System.Collections.IEnumerator effectCoroutine, System.Object options) (at /Plugins/WalletConnect/com.walletconnect.modal/Runtime/Views/ApprovalView/ApprovalView.cs:73)
> System.Runtime.CompilerServices.AsyncMethodBuilderCore+<>c.<ThrowAsync>b__7_0 (System.Object state) (at <4a4789deb75f446a81a24a1a00bdd3f9>:0)
> UnityEngine.UnitySynchronizationContext+WorkRequest.Invoke () (at <f712b1dc50b4468388b9c5f95d0d0eaf>:0)
> UnityEngine.UnitySynchronizationContext.Exec () (at <f712b1dc50b4468388b9c5f95d0d0eaf>:0)
> UnityEngine.UnitySynchronizationContext.ExecuteTasks () (at <f712b1dc50b4468388b9c5f95d0d0eaf>:0)

**Comment by skibitsky** [comment]
Hey @NotNasty,

Thanks! This is a known issue. Coinbase Wallet doesn't support the WalletConnect protocol and will be removed from that list in the future.

**Comment by skibitsky** [comment]
As a temporary workaround, you can exclude the Coinbase wallet from your app:
```csharp
var options = new WalletConnectModalOptions
{
    ConnectOptions = BuildConnectOptions(),
    ExcludedWalletIds = new[]
    {
        // Coinbase wallet ID from WalletConnect Explorer.
        // https://explorer.walletconnect.com/coinbase-wallet
        "fd20dc426fb37566d803205b19bbc1d4096b248ac04548e3cfb6b3a38bd033aa"
    }
};

WalletConnectModal.Open(options);
```

**Comment by skibitsky** [comment]
Fixed in [Reown AppKit](https://docs.reown.com/appkit/unity/core/installation) v1.1.0
