### ISSUE TITLE
DisconnectAsync method doesn't complete when there is no internet connection

### ISSUE THREAD

**Issue by astasovsky** [WalletConnect/WalletConnectUnity#201]
**Describe the bug**
WalletConnect.Instance.DisconnectAsync method doesn't complete when there is no internet connection

**To Reproduce**
1. Open app
2. Connect crypto wallet
3. Turn off the Internet
4. Disconnect crypto wallet
5. See that nothing happens (async operation is not completed or TimeoutException is not thrown)
6. Turn on the Internet
7. See that async operation is not completed or TimeoutException is not thrown

**Expected behavior**
DisconnectAsync method should send TimeoutException or complete

**Environment**
 - OS: macOS 14.3.1
 - Unity version 2021.3.23f1
 - Package name and version WalletConnectUnity Modal v1.1.2

**Is this happening in Unity Editor or on a player like Android, iOS, Windows?**
This is happening in Unity Editor and on Android. It hasn't been tested in iOS and Widows.

**Wallets used for testing**
Metamask Android, Trust Wallet Android

**Comment by skibitsky** [comment]
Fixed in WalletConnectUnity Modal v1.1.3
