### ISSUE TITLE
MetaMask will no longer show "Personal sign" popup if we close the MetaMask on the personal sign popup

### ISSUE THREAD

**Issue by astasovsky** [WalletConnect/WalletConnectUnity#202]
**Describe the bug**
MetaMask will no longer show "Personal sign" popup if we close the MetaMask on the "Personal sign" popup

**To Reproduce**
1. Open the app
2. Connect the crypto wallet
3. Click "personal_sign" button
4. Wait for the "Personal sign" popup to open in wallet app
5. **Close the wallet app**
6. Go back to your app
7. Repeat steps 2-3
8. Verify that wallet app doesn't show "Personal sign" popup

**Expected behavior**
Wallet app should show "Personal sign" popup

**Environment**
 - OS: macOS 14.3.1
 - Unity version 2021.3.23f1
 - Package name and version WalletConnectUnity Modal v1.1.2

**Is this happening in Unity Editor or on a player like Android, iOS, Windows?**
This is happening in Unity Editor and on Android. It hasn't been tested in iOS and Widows.

**Wallets used for testing**
 Metamask Android

**Additional context**
This could probably be a bug of the MetaMask app and not the WalletConnectUnity Modal. To make MetaMask show "Personal sign" popup again you need to reinstall the MetaMask app, clearing the app data does not help.

**Comment by skibitsky** [comment]
Thank you for opening the issue and providing all the details. Unfortunately, this is an issue with the MetaMask wallet and can only be fixed on their end. As far as I know, they will release improvements to their WalletConnect integration in the upcoming updates. Hopefully, this will resolve the issue.
