### ISSUE TITLE
Metamask jsonrpc error at sometimes

### ISSUE THREAD

**Issue by Dejavu0709** [WalletConnect/WalletConnectUnity#206]
**Describe the bug**
When we call a transaction，and estimate the gas，sometimes the metamask will return this error：
![FgfpVgIRzG](https://github.com/WalletConnect/WalletConnectUnity/assets/71498147/de9e0db2-cecb-4c67-84b1-ea9d5372bdba)

here is the code to estimate the gas and send transaction：

#region estimate gas

        var web3 = new Nethereum.Web3.Web3(RPC);
        var gasPrice  = await web3.Eth.GasPrice.SendRequestAsync();

        var routerContract = web3.Eth.GetContract(ABI, ContractAddress);
        var exactInputSingleFunction = routerContract.GetFunction("claimWithSig");

        Nethereum.Hex.HexTypes.HexBigInteger gasInput = new Nethereum.Hex.HexTypes.HexBigInteger("0x0");
        Nethereum.Hex.HexTypes.HexBigInteger value = new Nethereum.Hex.HexTypes.HexBigInteger("0x0"); 
        //Get gas estimate
        var gas = await exactInputSingleFunction.EstimateGasAsync(myAddress, gasInput, value, (UInt16)type, reward.open_id, (UInt16)reward.Multipier, reward.pay_free,
           _prizeNftAddress, _prizeNftTokenId, _prizeNftAmount,
            _prizeDamAddress, _prizeDamAmount,
            _prizeDioAddress, _prizeDioAmount, (UInt32)reward.deadline,
            signBytes);

        Debug.Log("gasPrice: " + gasPrice + " hex: " + gasPrice.Value.ToString("X"));
        Debug.Log("estimate gas: " + gas + " hex: " + (gas.Value).ToString("X"));

        #endregion

    var ethSendTransaction = new EthSendTransaction(new Transaction
        {
            From = myAddress,
            To = ContractAddress,
            Value = "0x" + reward.pay_free.ToString("X"),
            Data = data,
            Gas = (gas.Value).ToString("X"),
            GasPrice = gasPrice.Value.ToString("X")
        });

        try
        {

            var signClient = WalletConnect.Instance.SignClient;
            signClient.Options.RelayUrl = "wss://relay.walletconnect.org";
            Debug.Log(" signClient.Options.RelayUrl:" + signClient.Options.RelayUrl);
            var result = await WalletConnect.Instance.RequestAsync<EthSendTransaction, string>(ethSendTransaction, FullChainId);
            Debug.Log($"Transaction success! TxHash: {result}", this);
            if (result.Contains("0x"))
                callBackFunction?.Invoke(new RequestResult(true, reward));
            else
                callBackFunction?.Invoke(new RequestResult(false, reward));
            Debug.Log($"Transaction success! callBackFunction: ", this);
        }

**To Reproduce**
1. connect the metamask
2. send a transaction to estimate the gas

**Environment**
 - OS: [android]
 - Unity version [e.g. 2021.3.5f1]
 - Package name and version [e.g. WalletConnectUnity Modal v1.1.2]

**Wallets used for testing**
 [e.g. Metamask Android]

**Additional context**

**Comment by skibitsky** [comment]
This isn't a WalletConnect Modal issue. Please report it to MetaMask.
