### ISSUE TITLE
Vision Pro Unity Support

### ISSUE THREAD

**Issue by Biso240** [WalletConnect/WalletConnectUnity#223]
hi, I would like to ask if it is possible to make a version also for the vision pro as Unity modal does not work for it at the moment. A thousand thanks

**Comment by skibitsky** [comment]
Hello,

What exactly isn't working?

**Comment by Biso240** [comment]
When I try to build for visionOS(Windowed Mode), the unity compiler give me this errors(I'm logged because in the editor works): 
<img width="1504" alt="Screenshot 2024-04-30 alle 2 48 34 PM" src="https://github.com/WalletConnect/WalletConnectUnity/assets/73908461/6b187f17-4f87-46d4-aefd-1df50bd34386">

**Comment by skibitsky** [comment]
1. Did you install packages through OpenUPM or directly from git?
2. If you installed directly from git, do you also have `com.walletconnect.core` installed?
3. Are you encountering similar errors when the target platform is iOS?
4. What version of Unity are you using?

**Comment by skibitsky** [comment]
Unable to reproduce with Unity 2022.3.18. I don't get the errors.
![Screenshot 2024-04-30@2x](https://github.com/WalletConnect/WalletConnectUnity/assets/15127974/808d5361-8316-4a4c-9003-1d2e257f2686)

**Comment by Biso240** [comment]
also with your unity version doesn't work :(

**Comment by Biso240** [comment]
if I build in this way: like an IpadOS app, it works

<img width="766" alt="Screenshot 2024-04-30 alle 7 35 42 PM" src="https://github.com/WalletConnect/WalletConnectUnity/assets/73908461/e2d328a1-1c30-4f4a-8aad-06713910fe39">

**Comment by skibitsky** [comment]
Does it work for you in the Editor with VisionOS as the target platform?

**Comment by skibitsky** [comment]
I was able to reproduce it. It happens when building for VisionOS.

**Comment by skibitsky** [comment]
Temporary workaround
* Manually download packages directly into `Package` directory to enable write access
* From the Inspector enable `visionOS` platform for `Packages/com.walletconnect.core/Runtime/WalletConnectUnity.Core.asmdef` and apply changes
<img width=500 src=https://github.com/WalletConnect/WalletConnectUnity/assets/15127974/1d44fe23-2bbf-4fa4-80a5-7ba98576374d />

@Biso240 let me know if that helps. I'll include `visionOS` in the next release.

**Comment by skibitsky** [comment]
@Biso240, could you please test this PR? I also fixed the UI layout setting; it will now use wallet deep link by default , similar to how it works on mobile.

https://github.com/WalletConnect/WalletConnectUnity/pull/225

**Comment by Biso240** [comment]
Ok I can now build for VisionOs and build it into Vision Pro. After I got the same issue that you can find it also in IOS and Android. https://github.com/WalletConnect/WalletConnectUnity/issues/224

**Comment by skibitsky** [comment]
Nice, I'm working on #224, but it shouldn't block you from development. I'll try to release a fix next week.
