### ISSUE TITLE
Public Address

### ISSUE THREAD

**Issue by Kheemta** [WalletConnect/WalletConnectUnity#229]
i have connect wallet but issue is coming   when i connect wallet in android   how to get wallet address
    private async void InitialiseDapp(bool connected)
        {
           
            // SessionResumed is true if Modal resumed session from storage
            if (connected)
                EnableDappButtons();
            else
                EnableNetworksList();

            // Invoked after wallet connected
            WalletConnect.Instance.ActiveSessionChanged += (_, @struct) =>
            {
                Debug.Log(" "+ @struct.Topic);
                if (string.IsNullOrEmpty(@struct.Topic))
                    return;     
                EnableDappButtons();
            };
            // Invoked after wallet disconnected
            WalletConnect.Instance.SessionDisconnected += (_, _) =>
            {
                Debug.Log($"[WalletConnectModalSample] Session deleted.");
                EnableNetworksList();
            };
        }
please check this give me sulation when i connect  wallet public address Debug

**Comment by skibitsky** [comment]
Hey,

You can get an address like this:
```csharp
var session = WalletConnect.Instance.ActiveSession;
var sessionNamespace = session.Namespaces;
           
var address = WalletConnect.Instance.ActiveSession
                .CurrentAddress(sessionNamespace.Keys.FirstOrDefault())
                .Address;       
```
