### ISSUE TITLE
Session connection thread does not close when Unity project not playing

### ISSUE THREAD

**Issue by ghost** [WalletConnect/WalletConnectUnity#23]
Steps to reproduce:

1.) In the WalletConnectUnity demo project clear the session then provide a false custom bridge url like `ws://bananas:3434` (obviously there is no bridge server at this endpoint =P)

2.) Click play on the app - WalletConnect tries to connect to the bridge and fails.

3.) Stop the app - WalletConnect does not stop attempting to connect to the bridge server and repeats the following forever:
```
[WebSocket] OnError Unable to connect to the remote server
System.Exception: Unable to connect to the remote server
```

So it looks like the connection thread never gets shut down properly. Unity version tested with: 2020.3.18f1

This issue exists in the latest stable as well as PR21 versions of WCU.

**Comment by ecp4224** [comment]
This issue has been addressed in #21, will close when it gets merged

**Comment by eastedgeZack** [comment]
started running into this problem all of a sudden on Unity 2021.3.23f1
![Screen Shot 2023-06-28 at 1 22 38 PM](https://github.com/WalletConnect/WalletConnectUnity/assets/98972054/1638fef4-d40f-4ada-8f14-25f810fc7d13)

**Comment by gigajuwels** [comment]
closed due to v1 depreciation
