### ISSUE TITLE
While adding and switching chain, Error Received - User disapproved requested chains

### ISSUE THREAD

**Issue by deveshbeniwal** [WalletConnect/WalletConnectUnity#232]
**Describe the bug**
I was trying to switching the chain after user successfully connected to session.
**GOT THE ERROR - User disapproved requested chains**
**Wallet on which tried - MetaMask, TrustWallet**

**To Reproduce**
1. Connect wallet using sdk with namespace below -
```var requiredNamespaces = new RequiredNamespaces
        {
            {
                "eip155", new ProposedNamespace
                {
                    Methods = new[]
                    {
                        "eth_sendTransaction",
                        "eth_signTransaction",
                        "eth_sign",
                        "personal_sign",
                        "eth_signTypedData",
                        "wallet_addEthereumChain",
                        "wallet_switchEthereumChain"
                    },
                    Chains = new[]
                    {
                        "eip155:42161"
                    },
                    Events = new[]
                    {
                        "chainChanged",
                        "accountsChanged"
                    }
                }
            }
        };
```
2. Use the Extention method from WalletConnectUnity.Core.Evm i.e SwitchEthereumChainAsync
3. Create a method as below to switch chain -
```    private async Task CheckAndChange_ChainAsync()
    {
        string activeChain = WalletConnect.Instance.ActiveChainId;
        Debug.Log("Active chain: " + activeChain);

        Chain to_add_chain = ChainConstants.Chains.Arbitrum;
        try
        {
            Debug.Log("Switching chain...");
            await WalletConnect.Instance.SwitchEthereumChainAsync(new EthereumChain(to_add_chain));

            Debug.Log("Chain switched!");
        }
        catch (System.Exception e)
        {
            Debug.Log("error: " + e.Message);
        }
    }
```
4. In Editor it throws an error - **User disapproved requested chains** and in Android it opens metamask and immediately return back to our app with the same error - User disapproved requested chains

**Expected behavior**
It should show a popup in wallet to switch the chain and after switching we should get the event ActiveChainIdChanged

**Environment**
 - OS: Windows 11
 - Unity version - 2022.3.20
 - Package name and version - WalletConnectUnity Core(3.1.6), WalletConnectUnity Modal(1.1.6) and WalletConnectUnity UI(1.1.6)

**Is this happening in Unity Editor or on a player like Android, iOS, Windows?** 
Both Editor and Android

**Wallets used for testing**
Metamask, TrustWallet

**Comment by skibitsky** [comment]
Hello,

1. What version of MetaMask do you have?
2. Do you use Optional namespaces?
3. When you connect MetaMask, do you have Arbitrum as the active chain?

**Comment by deveshbeniwal** [comment]
Hi @skibitsky 
1. Metamask version - 7.22.0
2. No, I didn't know about optional namespaces, as i didn't found this on the documentation
3. No, It was Ethereum eip155:1, But tried changing the chains and add different chain but nothing happens

**Comment by skibitsky** [comment]
> No, I didn't know about optional namespaces, as i didn't found this on the documentation

Could you please try with optional namespaces? We use them in our sample app [here](https://github.com/WalletConnect/WalletConnectUnity/blob/a0a37c79c173bf2170933860c570606b5b5b44b5/Assets/Samples/WalletConnectUnity%20Modal/1.1.3/Modal%20Sample/Scripts/Dapp.cs#L140-L202).

**Comment by deveshbeniwal** [comment]
@skibitsky I followed that code, but still facing the same error again. Below is my methods to open the modal and switching the chain - 

Opening the modal -
```
public void Connect_Wallet()
{
    WalletConnectModal.Open(new WalletConnectModalOptions
    {
        ConnectOptions = BuildConnectOptions()
    });
}

private ConnectOptions BuildConnectOptions()
{
    HashSet<Chain> _selectedChains = new();
    _selectedChains.Add(ChainConstants.Chains.Ethereum);
    _selectedChains.Add(ChainConstants.Chains.Polygon);
    _selectedChains.Add(ChainConstants.Chains.Arbitrum);

    var optionalNamespaces = new Dictionary<string, ProposedNamespace>();

    var selectedEvmChains = _selectedChains.Where(c => c.ChainNamespace == ChainConstants.Namespaces.Evm).ToArray();
    if (selectedEvmChains.Any())
    {
        var methods = new[]
        {
            "wallet_switchEthereumChain",
            "wallet_addEthereumChain",
            "eth_sendTransaction",
            "personal_sign"
        };

        var events = new[]
        {
            "chainChanged", "accountsChanged"
        };

        var chainIds = selectedEvmChains.Select(c => c.ChainId).ToArray();
        optionalNamespaces.Add(ChainConstants.Namespaces.Evm, new ProposedNamespace
        {
            Chains = chainIds,
            Events = events,
            Methods = methods
        });
    }

    // Non-evm chain example.
    var algorandChains = _selectedChains.Where(c => c.ChainNamespace == ChainConstants.Namespaces.Algorand).ToArray();
    if (algorandChains.Any())
    {
        var methods = new[]
        {
            "algo_signTxn"
        };

        var events = new[]
        {
            "accountsChanged"
        };

        var chainIds = algorandChains.Select(c => c.ChainId).ToArray();
        optionalNamespaces.Add(ChainConstants.Namespaces.Algorand, new ProposedNamespace
        {
            Chains = chainIds,
            Events = events,
            Methods = methods
        });
    }

    if (optionalNamespaces.Count == 0)
        throw new InvalidOperationException("No chains selected");

    return new ConnectOptions
    {
        OptionalNamespaces = optionalNamespaces
    };
}
```

Code for adding and changing the chain - 

```
    public async Task Change_Chain()
    {
        Chain to_add_chain = ChainConstants.Chains.Polygon;
        try
        {
            Debug.Log("Switching chain...");
            await WalletConnect.Instance.SwitchEthereumChainAsync(new EthereumChain(to_add_chain));
            Debug.Log("Chain switched!");
        }
        catch (System.Exception e)
        {
            Debug.Log("error: " + e.Message);
        }
    }
```

**Comment by skibitsky** [comment]
I've tried your code, but I don't get any errors MetaMask 7.22.0 on Android.

If the active chain is not the one you are trying to switch to (in your case, Polygon), you should see this screen. Do you encounter the error after pressing the "Switch network" button or before?
<img width=300 src="https://github.com/WalletConnect/WalletConnectUnity/assets/15127974/80b44159-053f-4646-b5bd-f214b0af174a"/>

Have you tried sending other request, e.g. `personal_sign`? Do they also throw the error?

**Comment by deveshbeniwal** [comment]
Hi @skibitsky, It Worked but having another issue. 
Your confirmation helped me to notice that my code is fine but config was wrong so I noticed, I missed to filled the metadata in config file (Description, url and icons). I filled this and switching is working fine.

BUT

Switching is only working when the chain is already added to my network. When I try to add the network is giving the same error again - User disapproved the requested chains (even is not showing the popup to add the network).

Below is my code snippet to add the chain in network - 

```
        public async void Add_Chain()
        {
            Chain chain_to_add = ChainConstants.Chains.Polygon;
            EthereumChain ethereumChain_to_add = new EthereumChain(chain_to_add);

            WalletAddEthereumChain request_to_add = new WalletAddEthereumChain()
            {
                ethereumChain_to_add
            };

            var result_adding = await WalletConnect.Instance.RequestAsync<WalletAddEthereumChain, string>(request_to_add);
            Debug.Log(result_adding);
        }
```

**Comment by skibitsky** [comment]
Hey @deveshbeniwal, 

I'm glad you managed to make it work! I've replicated your second issue. This occurs because the default RPC in the `ChainConstants.Chains.Polygon` object is deprecated. I will update the RPC URL in the upcoming version. Meanwhile, you can duplicate the `ChainConstants.Chains.Polygon` object with a different RPC. You can find [a list of them here](https://chainlist.org/chain/137).

**Comment by deveshbeniwal** [comment]
Yes I also noticed the RPC urls was deprecated! I changed it and its working now!
Metamask is working fine but errors in trustwallet

**Comment by skibitsky** [comment]
MetaMask is the only wallet that needs chain switching. All other wallets, including Trust, support many chains simultaneously.
