### ISSUE TITLE
NEthereum extension support

### ISSUE THREAD

**Issue by ecp4224** [WalletConnect/WalletConnectUnity#24]
Currently need to overcome dependency conflicts, this should be easy since our only dependency is NewtonsoftJson which has a stable API between versions

Related discussions

> AlLansley
> what's your solution for WalletConnect and Nethereum both needing NewtonsoftJson? I've previously just deleted the WC version from the packages folder so it relies on the Nethereum one, but now it's spitting emit errors when I deploy to Android so I'm going to try to keep the WC one and do a binding redirect for Nethereum (perhaps related to the above?). Unfortunately it complains about a strongly referenced version of NewtonsoftJson 12.0.0 while the WC one is 10.0.0?
> Binding redirect steps I'm using: https://forum.unity.com/threads/dependency-on-newtonsoft-json.814128/#post-5398014

> ecp4224
> The ideal solution is to have the assembly for developers not using NEthereum (i.e using another web3 layer) and removing the assembly when NEthereum is being imported
> Another solution would be to just use Unity's built in NewtonsoftJson, however it's not clear what Unity version this is added in (2020.x)
> I have a WIP branch with the demo scene importing NEthereum however this assembly issue is present. This topic will be moved to it's own issue

**Comment by andrewnagata** [comment]
Hello. It appears that the following example code is deprecated. Is there a new way to use the Nethereum extension using Session rather than Protocol?

```
var wcProtocol = WalletConnect.Instance.Protocol
var web3 = new Web3(wcProtocol.CreateProvider(new Uri("https://mainnet.infura.io/v3/<infruaId>"));
```

**Comment by ecp4224** [comment]
If you have the latest WalletConnectSharp.NEthereum package in your project, you can create a `Web3` object by doing

```
WalletConnect.ActiveSession.BuildWeb3(rpcUrl).AsWalletAccount();
```

For legacy behavior of the package, you can use

```
WalletConnect.ActiveSession.BuildWeb3(rpcUrl).AsUnmanagedAccount();
```

**Comment by gigajuwels** [comment]
closed due to v1 depreciation
