### ISSUE TITLE
Installation progress is broken via github. Nethereum has wrong package name.

### ISSUE THREAD

**Issue by QuipHop** [WalletConnect/WalletConnectUnity#240]
**Describe the bug**
It's impossible to install WalletConnectUnity via github, Nethereum package is missed.
con.walletconnect.nethereum should be com.walletconnect.nethereum ?

**To Reproduce**
1. Follow README and try to install via github.
2. Stuck with a lot of messed packages.

**Expected behavior**
Installation progress should be clear with correct dependencies
**Screenshots**

**Environment**
 - Windows 10
 - Unity version [e.g. 2022.3.25f1]
 - WalletConnectUnity Modal v1.0.1]

**Is this happening in Unity Editor or on a player like Android, iOS, Windows?**

**Wallets used for testing**
Metamask 

**Additional context**

**Comment by skibitsky** [comment]
Hello @QuipHop,

Did you follow `Install via Package Manager with Git URL`? The Nethereum package is optional and shouldn't be breaking the installation of Core and Modal packages.

**Comment by QuipHop** [comment]
> Hello @QuipHop,
> 
> Did you follow `Install via Package Manager with Git URL`? The Nethereum package is optional and shouldn't be breaking the installation of Core and Modal packages.

Yes. The problem is you can't clone the repo or even download and unarchive zip without renaming deps.

**Comment by QuipHop** [comment]
Tried to reinstall everything within OpenUPM, got missed Nethereum refs.
Then tried to install Nethereum using Package Manager -> Add package by name -> com.walletconnect.nethereum

Got Error:
[Package Manager Window] Error adding package: com.walletconnect.nethereum.
Unable to add package [com.walletconnect.nethereum]:
  Package com.walletconnect.nethereum@1.0.1 has invalid dependencies or related test packages:
    com.nethereum.unity (dependency): Package [com.nethereum.unity@4.19.1] cannot be found

**Comment by skibitsky** [comment]
Thank you, I will look into git installation issue 🙏 

As for OpenUPM, the easiest approach is to use `openupm-cli` to install all packages including `com.walletconnect.nethereum`. The `com.walletconnect.nethereum` depends on official `com.nethereum.unity` which has a different scope (`com.nethereum`). The CLI tool adds all necessary scopes into the project manifest automatically. You can also do it manually.

**Comment by skibitsky** [comment]
The git installation issue was caused by the order in which packages were installed. It's important to follow a specific order to avoid compile errors that prevent subsequent package installations. I'll update the documentation to clarify this. Thanks for flagging it, @QuipHop 🙏 

You may also be interested in our AppKit solution for Unity, it has more features and Nethereum integration. There's a feature [comparison table here](https://github.com/WalletConnect/WalletConnectUnity?tab=readme-ov-file#appkit).

**Comment by QuipHop** [comment]
Got it, thank you @skibitsky
