### ISSUE TITLE
Bad comparison when setting up default wallets

### ISSUE THREAD

**Issue by bmateus** [WalletConnect/WalletConnectUnity#28]
In [WalletConnectSharp.Unity.WalletConnect::SetupDefaultWallet](https://github.com/WalletConnect/WalletConnectUnity/blob/34a7ed16c9231cdf62b087f29e18590084435ce0/Assets/WalletConnectUnity/Scripts/WalletConnectSharp.Unity/WalletConnect.cs#L333) there is a comparison between the enum Wallets name and the supported wallets names in https://registry.walletconnect.org/data/wallets.json that don't match.

For example, "Trust" vs. "Trust Wallet"

**Comment by ecp4224** [comment]
This has been fixed in #32
