### ISSUE TITLE
Suggestion: Have WalletConnectQRImage check for a QRCode in OnEnable

### ISSUE THREAD

**Issue by bmateus** [WalletConnect/WalletConnectUnity#29]
WalletConnectQRImage requires being enabled to set up the callback, but if the developer sets the game object inactive to hide it (perhaps to keep their scene tidy), this won't get called until the gameobject is activated at which point it might be too late and the image will never get updated. This might lead to some head-scratching... I'm suggesting refreshing the image in OnEnable (if it is able to)

**Comment by hanahdev** [comment]
> WalletConnectQRImage requires being enabled to set up the callback, but if the developer sets the game object inactive to hide it (perhaps to keep their scene tidy), this won't get called until the gameobject is activated at which point it might be too late and the image will never get updated. This might lead to some head-scratching... I'm suggesting refreshing the image in OnEnable (if it is able to)

we are so sorry for the late reply kindly contact there live chat support on whatsapp -  +19546679281

**Comment by gigajuwels** [comment]
closed due to v1 depreciation
