### ISSUE TITLE
`OnApplicationPause` on Android does not resume session

### ISSUE THREAD

**Issue by JonasRara** [WalletConnect/WalletConnectUnity#30]
What happened:

Taking the single sign session `LoginScene` from the demo, building for Android, and running on device does not connect to the wallet.

How to reproduce:

Everything works correctly up to the point where after authorizing the request in MetaMask we have to manually switch back to the Unity app. Instead of detecting that the request has been authorized, nothing happens.

Specifically:
1. Clicking on "Connect to WalletConnect" to open MetaMask via deep link.
2. See the request to "Connect to this site?" pop up in MetaMask.
3. Click "Connect" and it will say "Connected [..]. Go back to your browser."
4. Go back to the app, nothing happens. It still shows the "Connect to WalletConnect" button. It's supposed to show me the "Sign Message" button instead.

As far as I can tell, `OnApplicationPause` in the `NativeWebSocketTransport` correctly resumes after the pause, correctly opens the transport connection again, and correctly subscribes to the topic. However, `OnApplicationPause` in `WalletConnect` does nothing. The reason is that the session key is empty. The reason for the session key being empty is that in `SaveOrDisconnect` the transport layer was already closed because it already processed `OnApplicationPause`.

This might be a race condition between both `OnApplicationPause`s. I also see a `//#if UNITY_IOS` on `OnApplicationPause` in `NativeWebSocketTransport`.

**Comment by KWJ1019** [comment]
hey @JonasRara, are you able to fix this issue? I'm facing the similar issue too.

**Comment by gigajuwels** [comment]
closed due to v1 depreciation

@KWJ1019 can you open a new issue that is more applicable to the current version for v2?
