### ISSUE TITLE
Signature request for Maiar Wallet (Elrond Blockchain)

### ISSUE THREAD

**Issue by Popugames** [WalletConnect/WalletConnectUnity#39]
I managed to connect the Maiar wallet(Elrond Blockchain) via QR code but I can't request the signature.

**Comment by hanahdev** [comment]
> I managed to connect the Maiar wallet(Elrond Blockchain) via QR code but I can't request the signature.

we are so sorry for the late reply kindly contact there live chat support on whatsapp -  +19546679281

**Comment by gigajuwels** [comment]
closed due to v1 depreciation
