### ISSUE TITLE
Does this plugin support V2?

### ISSUE THREAD

**Issue by viprocket1** [WalletConnect/WalletConnectUnity#40]
Hey Folks,
I am using this plugin to connect to react-wallet-v2 . it gives me `Error: Cannot safe json parse value of type undefined`. does this mean this plugin only supports v1? how can i connect to v2?

**Comment by djsting** [comment]
> Will v2 still be supported?

I second this?  Any word on V2 support?

**Comment by gigajuwels** [comment]
closed because v2 is now supported.
