### ISSUE TITLE
Is it possible to retrieve wallet name after resuming session?

### ISSUE THREAD

**Issue by MarwenSami** [WalletConnect/WalletConnectUnity#43]
Hello,

I'm getting `You must use OpenMobileWallet(AppEntry) or set SelectedWallet on iOS!` exception after calling `OpenMobileWallet()` on iOS device when resuming a previous session.
To fix this I'm saving the `SelectedWallet` value in a PlayerPrefs and reloading it when a session is resumed.
Is it possible to retrieve the wallet `AppEntry` after resuming session directly from the `WalletConnect` singleton?

Thanks,

**Comment by hanahdev** [comment]
> Hello,
> 
> I'm getting `You must use OpenMobileWallet(AppEntry) or set SelectedWallet on iOS!` exception after calling `OpenMobileWallet()` on iOS device when resuming a previous session. To fix this I'm saving the `SelectedWallet` value in a PlayerPrefs and reloading it when a session is resumed. Is it possible to retrieve the wallet `AppEntry` after resuming session directly from the `WalletConnect` singleton?
> 
> Thanks,

we are so sorry for the late reply kindly contact there live chat support on whatsapp -  +19546679281

**Comment by ecp4224** [comment]
Are you looking for `WalletConnect.ActiveSession.WalletMetadata` ? This is an object of type `ClientMeta` which includes things like `Name`, `Icons` (urls), `URL` and `Description`

**Comment by MarwenSami** [comment]
That would work, however it's confusing to expect the Wallet's metadata to be in the same class as the client's metadata.
It would be more logical to store it in an `AppEntry` object.
Thanks for the help.

**Comment by gigajuwels** [comment]
issue has been resolved.
