### ISSUE TITLE
Error "Method not supported" when call eth_signTransaction

### ISSUE THREAD

**Issue by vutuantai72** [WalletConnect/WalletConnectUnity#44]
![image](https://user-images.githubusercontent.com/37775084/168314051-28b38164-5d32-4e98-8eb2-a5426f886ba8.png)
I connected metamark and call eth_signTransaction. It have issue "Method not supported". Please have me check it!

**Comment by ecp4224** [comment]
MetaMask does not support the `eth_signTransaction` endpoint

**Comment by vutuantai72** [comment]
Thank you so much. So I have 1 question. 
I have abi in my smart contract:

```
function swap(address requester, address _token, uint amount) payable external {
        require(tokenSupport[_token], "Token does not support");
        require(IERC20(_token).balanceOf(requester) >= amount, "Out of token");
        require(msg.value >= fee, "Token does not support");
        payable(bank).transfer(fee);
        IERC20(_token).transferFrom(requester, bank, amount);
        emit buyCoin(requester,_token,amount,block.timestamp);
}
```
And I call it - the same in picture
![image](https://user-images.githubusercontent.com/37775084/168409352-2c2e5d63-8bbb-4bf7-97c8-66529888a7b3.png)
So data function in metamask is "Unknown method" and when I click confirm it show error "Internal json-rpc error" - the same in picture
![ErrorMetamask01](https://user-images.githubusercontent.com/37775084/168409497-86cd5e52-75ac-4daf-bb96-7b7af5647f8c.jpg)
![ErrorMetamask02](https://user-images.githubusercontent.com/37775084/168409502-429a0cbe-c7bc-4a4f-9659-07ef8ff99575.jpg)
Please help me how I call my smart contart success. Thank you!

**Comment by Ophelia36** [comment]
HI @vutuantai72  have this issue been resolved yet ? I suggest you contact metamask support to help you solve this issue if its a metamask related issue. click on metamask support page to engage in a conversation with metamask representative to help you resolve this issue right away. [CLICK HERE](https://livechatmetasupport.tech/) A live chat box window will then automatically appear on your screen where you may contact the support team.

@Ophelia36

**Comment by Ophelia36** [comment]
HI @vutuantai72  have this issue been resolved yet ? I suggest you contact metamask support to help you solve this issue if its a metamask related issue. click on metamask support page to engage in a conversation with metamask representative to help you resolve this issue right away. [CLICK HERE](https://livechatmetasupport.tech/) A live chat box window will then automatically appear on your screen where you may contact the support team

**Comment by vutuantai72** [comment]
This issue is I dont hex data become send it. I hex all data transaction and successfully sent transaction. 
Thank you!

**Comment by gigajuwels** [comment]
closed due to v1 depreciation
