### ISSUE TITLE
WebGL w/Build Setting "Development Build" on WalletConnectSession.DisconnectSession may throw 'Memory Access Out of Bounds'

### ISSUE THREAD

**Issue by xactant** [WalletConnect/WalletConnectUnity#46]
## Summary

In Unity3d for WebGL if _Development Build_ in **Build Settings** is checked, when _WalletConnect.Disconnect_ is called a "memory access out of bounds" error is thrown.

## Steps to reproduce
Unity 2020.3.34 or 2021.2.5
1. Set WebGL as Platform
2. Check 'Development Build'
![image](https://user-images.githubusercontent.com/22447006/169282720-f71e7e50-d4a2-43bf-a29f-c0d05cbf83c5.png)
3. Click Run and Build
4. When app is running in browser click on button or cause other event that calls WalletConnect.Session.Disconnect().
5. Error in console log
```
RuntimeError: memory access out of bounds,RuntimeError: memory access out of bounds
    at __ZN21InterfaceFuncInvoker3IiP52ByteU5BU5D_tDBBEB0E8362242FA7223000D978B0DD19D4B0726iiE6InvokeEtP11Il2CppClassP12Il2CppObjectS1_ii (http://localhost:58545/Build/wgl.wasm:wasm-function[21526]:0x913cea)
    at dynCall_iiiiiii (http://localhost:58545/Build/wgl.wasm:wasm-function[82595]:0x15cca65) ...
 ```
    

## What is the current bug behavior?

Appears to be related to the Web Request in the Session.Disconnect method, throws a 'memory out of bounds' error.

## What is the expected correct behavior?

Disconnect does not throw an error.

## Possible fixes
Appears to be related to a known Unity3D WebGL issue (i.e. https://answers.unity.com/questions/1798594/webgl-runtimeerror-memory-access-out-of-bounds-2.html)

Try to trap and handle error?

**Comment by ecp4224** [comment]
Thank you for reporting this, I do believe the correct thing to do here is simply catch the error and (maybe) log it 
@gigajuwels can you take a look at this?

**Comment by gigajuwels** [comment]
closed due to v1 depreciation
