### ISSUE TITLE
Slow response from bridge server only IOS device

### ISSUE THREAD

**Issue by KamilGawelek1** [WalletConnect/WalletConnectUnity#47]
### Summary
Slow response from bridge server bug apear maybe half month ago. on Android working fine.

### **Steps to reproduce**
Unity 2020.3.1f or 2021.2.5

build this repo to ios devices
try connect wallet to metamask
after clicking connect app in metamask go to app previous opened
now you have to wait 1 minute to be call Connected Event

### What is the current bug behavior?
Appears to be related to the bridge server with (alphanumeric).bridge.walletconnect slow response of session

### What is the expected correct behavior?
instant connect with connected event called.

### Possible fixes
 
https://user-images.githubusercontent.com/83002252/172593459-d6aa7516-26d8-4d68-a145-50be7d0f9ae4.jpg

**Comment by gigajuwels** [comment]
closed due to v1 depreciation
