### ISSUE TITLE
How to checkout default wallet?

### ISSUE THREAD

**Issue by boy-good** [WalletConnect/WalletConnectUnity#49]
First time to open the WalletConnectUnity in android,has TokenPocket and Metamask. I select the TokenPocket and check do not prompt again. The second time it is no longer selectable MetaMask, even if I uninstall and then reinstall it defaults to TokenPocket. How do i to deal it?Thanks.

**Comment by boy-good** [comment]
What should I do if I want to remove the built-in wallet selection pop-up box?I want to click the button and link him to the MetaMask,just use # Example
wc:00e46b69-d0cc-4b3e-b6a2-cee442f97188@1?bridge=https%3A%2F%2Fbridge.walletconnect.org&key=91303dedf64285cbbaf9120f6e9d160a5c8aa3deb67017a3874cd272323f48ae ?

**Comment by ecp4224** [comment]
What platform are you testing on? Usually on Android this is a system default that needs to be changed in the system settings if it was set

On iOS, the drop-down should control which app opens

**Comment by boy-good** [comment]
Okay thanks Penta @ecp4224  The drop-down how to cancel? I want to control which app opens by our own UI ^_^

**Comment by gigajuwels** [comment]
closed due to v1 depreciation
