### ISSUE TITLE
Unable to properly sign a message with escaped string like `\n`

### ISSUE THREAD

**Issue by michitomo** [WalletConnect/WalletConnectUnity#56]
When you try to sign a message that includes escaped string like `\n`, the library can't handle it properly.

For example, if we want to sign
```
Hello,
I am signing a message
```
The user should be able to sign and confirm a mesage like this on MetaMask
<img src="https://user-images.githubusercontent.com/456182/185766369-219c8dcd-13b5-4720-9c2a-e670cb54eed4.png" width="200px">
However, because of the current implementation, a message you can sign will be this instead
<img src="https://user-images.githubusercontent.com/456182/185766400-5b69167c-4646-40cb-8745-8594418804f4.png" width="200px">

I have a pull request who needs an immediate fix but I would want somebody good in C# to write a proper fix.

**Comment by ecp4224** [comment]
Is the `\\n` coming from the input in Unity or somewhere else?

**Comment by michitomo** [comment]
@ecp4224 Oh this might be a good point. For my usecase, it is coming from..

The original message is from https://docs.lens.xyz/docs/login. The double-escape issues might be happening during the JSON deserialization.

**Comment by gigajuwels** [comment]
closed due to v1 depreciation
