### ISSUE TITLE
(Android / iOS) OpenDeepLink(AppEntry app) doesn't work correct with set wallet

### ISSUE THREAD

**Issue by Sergan4ik** [WalletConnect/WalletConnectUnity#58]
When trying to open a wallet for auth in the app from the next code, get invalid behavior.
```
public WalletConnect Connect => WalletConnect.Instance;
private AppEntry MetaMask => Connect.SupportedWallets.First(w => w.Value.name == nameof(MetaMask)).Value;
............
............
private void OpenMetamask() => Connect.OpenDeepLink(MetaMask);
```
When using the function OpenMetamask firstly - just open the wallet, with biometric verification, without any auth popup. Next, if I'll return to the app, and again press "Connect Metamask", Metamask will open with auth popup. I think it happened because of pausing my dapp , when switching applications with additional verification (like PIN, or biometric) on my OS (Android, but iOS the same issue), but don't know how to fix it.

**Comment by gigajuwels** [comment]
closed due to v1 depreciation
