### ISSUE TITLE
Mobile wallet not receiving transactions for signing when wallet connect is running on AWS EC2 instance.

### ISSUE THREAD

**Issue by JoshOtter** [WalletConnect/WalletConnectUnity#59]
I've made a Unity build to test running Wallet Connect on an AWS EC2 instance while a client connects to it. In this way, the EC2 instance sends the URI info for the QR code to the client for connecting to Wallet Connect. This part works fine. I can connect and disconnect from Wallet Connect through this remote connection as much as I like, but for some reason I'm having trouble getting transaction requests sent to my mobile wallet.

When I tested the server client interactions locally, everything worked fine and I was able to sign for transactions, but now that I'm using the actual EC2 instance (I've tried both Linux and Windows), it doesn't even give me an error prompt for the signature request.
And the weird thing is that I actually did get an error message on my mobile wallet when the asset id I was using for payment was wrong. It's only when all the values are correct that it does nothing.

Is there something about running WalletConnectUnity on an EC2 instance that would cause this issue when sending requests to wallet connect?

**Comment by ecp4224** [comment]
I would see if the AWS EC2 instance is blocking the websocket connection through a firewall rule. This is how the bidirectional communication is done between the Wallet (or `WalletConnectProvider` in future 1.8 release) and the `WalletConnectSession` instance.

The default ports for websocket over `wss` is 443 and 80 for `ws`. However, this may be different depending on what is defined in the qrcode URL.

**Comment by JoshOtter** [comment]
Thank you for your answer. I'm sorry I wasn't able to readdress this until today. I found out that the Linux instances I'm using do not have ports 80 or 443 open, so I thought I'd try specifying a custom port in the URL that are open. However, I'm not sure if I included it in the URL string correctly. Just to give it a try I added ":7770" immediately after the bridge URL like this:
```
        public string URI
        {
            get
            {
                var topicEncode = WebUtility.UrlEncode(_handshakeTopic);
                var versionEncode = WebUtility.UrlEncode(Version);
                var bridgeUrlEncode = WebUtility.UrlEncode(_bridgeUrl);
                var keyEncoded = WebUtility.UrlEncode(_key);

                return "wc:" + topicEncode + "@" + versionEncode + "?bridge=" + bridgeUrlEncode + ":7770&key=" + keyEncoded;
            }
        }
```
The result was that the wallet app gave an error message after several seconds that said the dapp wasn't responding. Did I include the port incorrectly in the URL string for Wallet Connect, or do you think I should be looking elsewhere for the cause of this issue?

**Comment by gigajuwels** [comment]
closed due to v1 depreciation
