### ISSUE TITLE
Custom Contract interaction

### ISSUE THREAD

**Issue by agelessZeal** [WalletConnect/WalletConnectUnity#60]
Is there any example of interacting with the custom function of the contract?

**Comment by goldnite** [comment]
Hi @agelessZeal.
You need to use Nethereum library to make custom contract interaction.
Please refer Nethereum docs at https://docs.nethereum.com/en/latest/.
If you have any problem with it, please feel free to post here.

**Comment by gigajuwels** [comment]
closed due to v1 depreciation
