### ISSUE TITLE
Is v2 available for Unity ? Trustwallet is not responding after scanning walletconnect qr code

### ISSUE THREAD

**Issue by Yozaak** [WalletConnect/WalletConnectUnity#63]
Hi, is v2 protocol update coming for unity as well ? Trustwallet is no longer responding when I can qr code generated by walletconnect. Metamask seems to be working fine.

**Comment by CustomerTeam001** [comment]
We'd be happy to look into this for you 
kindly file a support ticket below 
https://forms.gle/FhSmn4AznQtZcruX8

**Comment by KBryan** [comment]
Doesn't seem to be to much traction on this. I will be looking into it as we need also. Will keep you posted on the progress.

**Comment by gigajuwels** [comment]
v2 is available now
