### ISSUE TITLE
Do not use .NET packages

### ISSUE THREAD

**Issue by Popugames** [WalletConnect/WalletConnectUnity#71]
Hello.
To see if WalletConnect is compatible with all devices, please Build and Run on WebGL. 

Certain .NET packages are not compatible with Unity or the code is deformed after compiling with IL2CPP.

On my Unity project, WalletConnect v2.0 works on Editor but after build do not work.

Thank you.

**Comment by gigajuwels** [comment]
this has been fixed in the latest commit.
