### ISSUE TITLE
Base64UrlEncoder C# version error

### ISSUE THREAD

**Issue by WoodsFiend** [WalletConnect/WalletConnectUnity#72]
The Base64UrlEncoder has an issue with how string decoding is done. 

This doesn't work in Unity 2020.3.41f which uses C# 8.0, it says I must be on C# 9.0 or greater
```
string decodedString = new(char.MinValue, decodedLength);
```

The error seems to go away when I use string
```
string decodedString = new string(char.MinValue, decodedLength);
```

**Comment by gigajuwels** [comment]
this issue has been resolved in the latest commit.
