### ISSUE TITLE
Interface Errors

### ISSUE THREAD

**Issue by WoodsFiend** [WalletConnect/WalletConnectUnity#73]
Several interfaces are throwing errors when I import into Unity 2020.3.41f

- ICore
- IRelayer
- IAcknowledgement
- IApprovedData

```
 error CS8701: Target runtime doesn't support default interface implementation.
```

**Comment by skibitsky** [comment]
WalletConnectUnity needs netstandard 2.1. You should upgrade Unity version to 2021.3 or newer.
