### ISSUE TITLE
Unable to connect as of 28/6 using 2021.3 LTS

### ISSUE THREAD

**Issue by 0xFirekeeper** [WalletConnect/WalletConnectUnity#74]
Repro steps:
- Clone repo
- Open `SimpleUnityDapp` scene, no changes
- Press play

74 warnings show up, mostly missing scripts, but they are warnings, so I am able to select a chain and press 

From there, selecting  a chain and pressing connect either:
- Logs `Connecting sign client..` before hanging indefinitely 
- Generates a QR code successfully and prompts a wallet (that supports these RPC methods) to connect, but hangs on `await connectData.Approval;` indefinitely, never getting a callback

This is the same behaviour I would get by initializing the SDK as per your [docs](https://docs.walletconnect.com/2.0/unity/sign/installation) in a fresh project with dlls imported into unity.

Other minor observations:
- Importing the raw scripts with `unsafe` keyword means you have to allow it explicitly in project settings
- If the target framework is .NET Framework rather than .NET Standard 2.1 in Unity your System.Web reference is lost and throws an error, to fix you should include it or reference it with a `csc.rsp` under Assets
- The QR code is on the far left of the scene, not rendered in the gameview 
- Rainbow wallet seems to throw errors while Metamask hangs, either way I can't seem to connect wallets

If you have a working scenario, please advise.

**Comment by WoodsFiend** [comment]
@0xFirekeeper Are you using the latest 2.0? The default branch was just changed to it yesterday after Wallet Connect 1.0 was deprecated.

**Comment by 0xFirekeeper** [comment]
Yes I am

**Comment by WoodsFiend** [comment]
I am having same issue now that upgraded to Unity 2021 and got past all the other errors I ran into.

**Comment by youngether** [comment]
I meet same bug. Please add some guide, how to use walletconnectv2.

**Comment by gigajuwels** [comment]
Hi,

I am able to reproduce this issue with MetaMask. This scene was tested with Trust Wallet on Windows, OSX and Linux. Can you confirm this works with Trust Wallet?

It seems MetaMask is not sending a response when accepting the connection, which is causing the hang. 

> The QR code is on the far left of the scene, not rendered in the gameview

I've updated the scene to fix this issue

> Rainbow wallet seems to throw errors while Metamask hangs, either way I can't seem to connect wallets

Do you have the errors Rainbow is throwing? Perhaps the initial request isn't formatted properly? I wonder why Trust Wallet seems to work fine

> Importing the raw scripts with unsafe keyword means you have to allow it explicitly in project settings
If the target framework is .NET Framework rather than .NET Standard 2.1 in Unity your System.Web reference is lost and throws an error, to fix you should include it or reference it with a csc.rsp under Assets

These issues will be fixed thank you for the suggestion

**Comment by 0xFirekeeper** [comment]
Hi @gigajuwels thanks for getting back to me.

I can confirm Trust Wallet does connect when choosing a valid network such as Ethereum mainnet, however the following UI with signing buttons do not work.

As for Metamask your description is correct, no response is sent back.

Here are the logs of what I get when connecting to Rainbow:

```
System.AggregateException: One or more errors occurred. (Invalid session extend request) ---> WalletConnectSharp.Common.Model.Errors.WalletConnectException: Invalid session extend request
   --- End of inner exception stack trace ---
  at System.Threading.Tasks.Task.ThrowIfExceptional (System.Boolean includeTaskCanceledExceptions) [0x00011] in <1c8569827291471e9db0dcd976e97952>:0 
  at System.Threading.Tasks.Task`1[TResult].GetResultCore (System.Boolean waitCompletionNotification) [0x0002b] in <1c8569827291471e9db0dcd976e97952>:0 
  at System.Threading.Tasks.Task`1[TResult].get_Result () [0x0000f] in <1c8569827291471e9db0dcd976e97952>:0 
  at WalletConnect.WCSignClient.<Connect>b__48_0 (System.Threading.Tasks.Task`1[TResult] task) [0x00000] in D:\Projects\WalletConnectUnity\Assets\WalletConnectUnity\Scripts\WalletConnectUnity\WCSignClient.cs:112 
  at (wrapper delegate-invoke) System.Func`2[System.Threading.Tasks.Task`1[WalletConnectSharp.Sign.Models.SessionStruct],WalletConnectSharp.Sign.Models.SessionStruct].invoke_TResult_T(System.Threading.Tasks.Task`1<WalletConnectSharp.Sign.Models.SessionStruct>)
  at System.Threading.Tasks.ContinuationResultTaskFromResultTask`2[TAntecedentResult,TResult].InnerInvoke () [0x00024] in <1c8569827291471e9db0dcd976e97952>:0 
  at System.Threading.Tasks.Task.Execute () [0x00000] in <1c8569827291471e9db0dcd976e97952>:0 
--- End of stack trace from previous location where exception was thrown ---

  at WalletConnectUnity.Demo.SimpleSign.ConnectScreen.OnConnect () [0x0020e] in D:\Projects\WalletConnectUnity\Assets\WalletConnectUnity\Demo\SimpleSign\Scripts\ConnectScreen.cs:83 
---> (Inner Exception #0) WalletConnectSharp.Common.Model.Errors.WalletConnectException: Invalid session extend request<---

UnityEngine.Debug:LogError (object)
WalletConnectUnity.Demo.SimpleSign.ConnectScreen/<OnConnect>d__3:MoveNext () (at Assets/WalletConnectUnity/Demo/SimpleSign/Scripts/ConnectScreen.cs:99)
UnityEngine.UnitySynchronizationContext:ExecuteTasks ()
```
On the Rainbow UI, it shows "Connection failed, something went wrong. Please try again, or reach out to our support team".

I think having Metamask, Trust and Rainbow wallet support would be a great start to using this.

Sidenote: I had to remove some RPC requests from the initialization for it to prompt connection with Rainbow, as some aren't supported.

**Comment by 0xFirekeeper** [comment]
Managed to get connecting (not disconnecting) to work porting [2.0.6](https://www.nuget.org/packages/WalletConnect.Sign/2.0.6)

Requests of any kind seem to crash Unity, or throw internal error

Would appreciate some examples for personal_sign etc. that might work. 

So far tried with
```cs
[RpcMethod("personal_sign")]
public class WalletConnectPersonalSignRequest
{
    public string message { get; set; }
    public string account { get; set; }
}
```
with and without Clock parameters, as well as the WalletConnectSharp test examples, no luck.

Perhaps Unity needs its own custom implementation?

**Comment by GaoG001108** [comment]
@gigajuwels

**Comment by 0xFirekeeper** [comment]
Seems to be working with the native websocket now, thanks!

**Comment by fudgebucket27** [comment]
@0xFirekeeper ive been trying to figure out personal sign for a while now to no avail. could you provide the sample code please? sorry to ask..

**Comment by fudgebucket27** [comment]
@0xFirekeeper  mate thank you! that got it to work. im making a blazor wasm template with wallet connections to Loopring related wallets! You can view the code for the WalletConnect portion here: https://github.com/fudgebucket27/BlazeRing/blob/master/BlazeRing/Client/Shared/WalletConnect.razor 

Very much a work in progress
