### ISSUE TITLE
QR Code Scan not responding in WalletConnectUnity SimpleUnityDapp scene

### ISSUE THREAD

**Issue by yozdev** [WalletConnect/WalletConnectUnity#75]
Hello Team,

I imported the latest assets from 2.0 branch in my Unity project.

While running the SimpleUnityDapp Demo scene in the editor, I noticed that scanning the generated QR code does nothing. I don't receive any notification on my app nor any logs in the editor.

I also received missing scripts warning in the console when starting the scene. Also noticed some missing scripts references on the QR gameobjects.

I'm attaching screenshots of the warnings and QR gameobject.

Please guide me on how to use the QR code scanner in v2.

<img width="1920" alt="QR Missing Script" src="https://github.com/WalletConnect/WalletConnectUnity/assets/113970224/641d5576-9f3f-4065-be35-021f81e06bb3">

<img width="1920" alt="Missing scripts" src="https://github.com/WalletConnect/WalletConnectUnity/assets/113970224/fb30e982-28a1-43bd-8238-7387006b35f3">

**Comment by skibitsky** [comment]
Hello,

Please try again with the latest version of WalletConnectUnity and make sure your wallet supports the chosen chain. By default SimpleUnityDapp suggest testnets which some mobile wallets may no support.
