### ISSUE TITLE
How must I setup the .NET compatibility for this code to work?

### ISSUE THREAD

**Issue by luismasuelli** [WalletConnect/WalletConnectUnity#77]
I followed the README.md and get several syntax errors (errors around the `new` keyword, namespace declarations, ...). What's the .NET compatibility I must use? (considering that right now I'm using Unity 2020.3.x).

**Comment by bulleador** [comment]
If you have issues like this, there might be something fundamentally wrong with your Unity setup and it's probably not even close to being related to WalletConnect
