### ISSUE TITLE
WHY V1 WAS CLOSED?????

### ISSUE THREAD

**Issue by alibk1** [WalletConnect/WalletConnectUnity#78]
Guys I am using WalletConnect to allow my users connect to their METAMASK wallets on Android.  It was working fine but seems like you shutted down your v1 servers and I am getting error :

System.Exception: Unable to connect to the remote server
UnityEngine.Debug:LogError (object)
WalletConnectSharp.Unity.Network.NativeWebSocketTransport:HandleError (System.Exception)

GUYS WHY?

I need to send new update to my client  tomorrow and thx to u , there are broken functions in my app. WHAT SHOULD I DO TO CONNECT METAMASK ON ANDROID?

**Comment by gigajuwels** [comment]
You can use v2, it supports mobile & metamask. this change was due to the sunset of v1
