### ISSUE TITLE
Connect websocket failed with socket stalled

### ISSUE THREAD

**Issue by funnyData** [WalletConnect/WalletConnectUnity#79]
Hi,

I have downloaded the project and click play to start. I shows the wallets list well, but after 5 seconds, it shows socket connect timeout with socket stalled, I can't solve this by my self, can anyone help me with this? thanks!

![image](https://github.com/WalletConnect/WalletConnectUnity/assets/5466601/aea43a56-3ed7-40c2-840c-2b817c67aff2)

**Comment by funnyData** [comment]
Cannot connect to relay server

**Comment by GaoG001108** [comment]
i have the same problem,Have you resolved it？

**Comment by defchen** [comment]
yeah, it seems this project is not being taken seriously

**Comment by gigajuwels** [comment]
hi @defchen @GaoG001108 @funnyData this issue should be fixed now, as the simple dapp demo is fully working on desktop and mobile. Can you confirm this issue is resolved? If not, can you provide some details on how you reproduce this and what error you are getting?
Thank you

**Comment by zy-game** [comment]
This problem still exists

**Comment by zy-game** [comment]
> This problem still exists



> hi @defchen @GaoG001108 @funnyData this issue should be fixed now, as the simple dapp demo is fully working on desktop and mobile. Can you confirm this issue is resolved? If not, can you provide some details on how you reproduce this and what error you are getting? Thank you
This problem still exists

**Comment by skibitsky** [comment]
Fixed by https://github.com/WalletConnect/WalletConnectSharp/pull/124
