### ISSUE TITLE
Socket connection failed

### ISSUE THREAD

**Issue by GaoG001108** [WalletConnect/WalletConnectUnity#80]
![image](https://github.com/WalletConnect/WalletConnectUnity/assets/121652682/ae4b6313-5b14-47cf-b23a-10c37c4c6e9e)
May I ask if everyone has encountered this problem and has it been resolved

**Comment by funnyData** [comment]
NO, have you found some way to solve it?

**Comment by GaoG001108** [comment]
This issue is related to one's own local network
