### ISSUE TITLE
Auth is error

### ISSUE THREAD

**Issue by GaoG001108** [WalletConnect/WalletConnectUnity#81]
The auth generated after packaging is different from the one generated without packaging, and the socket has been unable to connect. Do you have any suggestions for this issue
![image](https://github.com/WalletConnect/WalletConnectUnity/assets/121652682/932474ed-ac66-40a0-a572-cd0db69a8295)

**Comment by GaoG001108** [comment]
@ecp4224

**Comment by funnyData** [comment]
@GaoG001108 Hi buddy, How did you solve the socket stalled error, can you guide me?

**Comment by GaoG001108** [comment]
> 

Not resolved yet, waiting for official response @funnyData

**Comment by skibitsky** [comment]
Hey @funnyData, @GaoG001108! Do you still experience the issue? Could you provide more info, please?
