### ISSUE TITLE
eth_sendtransaction request

### ISSUE THREAD

**Issue by GaoG001108** [WalletConnect/WalletConnectUnity#82]
Hello, I look forward to your reply very much. I noticed that you updated the warehouse of Unity yesterday, but it is still not possible to initiate a request by cloning the latest one. After calling the request interface, I did not receive any response or error. The following is my request data.
![image](https://github.com/WalletConnect/WalletConnectUnity/assets/121652682/a0bc6e87-4fa0-4cb0-91a8-aeab07c857b2)

**Comment by GaoG001108** [comment]
@ecp4224

**Comment by skibitsky** [comment]
Please try again using latest SDK version and provide more context (OS, Unity version, wallets used, etc) if the issue persists.
