### ISSUE TITLE
Null Reference error while running Desktop build of Demo scene

### ISSUE THREAD

**Issue by yozdev** [WalletConnect/WalletConnectUnity#83]
Hello Team,

This is related to the WalletConnectUnity version from https://github.com/WalletConnect/WalletConnectUnity/tree/2.0.

I'm using Unity version 2021.3.23f1

When I run the SimpleUnityDapp demo scene in Unity Editor, it runs fine without any errors.

However, when I make a Windows build and run it, it gives the following error after I choose a chain from the list and press Connect button

Console Log Error :

NullReferenceException: Object reference not set to an instance of an object.
WalletConnect.WCSignClient.Connect (WalletConnectSharp.Sign.Models.Engine.ConnectOptions options) (at <00000000000000000000000000000000>:0)
System.Runtime.CompilerServices.AsyncTaskMethodBuilder1[TResult].Start[TStateMachine] (TStateMachine& stateMachine) (at <00000000000000000000000000000000>:0) WalletConnect.WCSignClient.Connect (WalletConnectSharp.Sign.Models.Engine.ConnectOptions options) (at <00000000000000000000000000000000>:0) WalletConnectUnity.Demo.SimpleSign.ConnectScreen.OnConnect () (at <00000000000000000000000000000000>:0) System.Runtime.CompilerServices.AsyncVoidMethodBuilder.Start[TStateMachine] (TStateMachine& stateMachine) (at <00000000000000000000000000000000>:0) WalletConnectUnity.Demo.SimpleSign.ConnectScreen.OnConnect () (at <00000000000000000000000000000000>:0) UnityEngine.Events.InvokableCall.Invoke (System.Object[] args) (at <00000000000000000000000000000000>:0) UnityEngine.Events.UnityEvent.Invoke () (at <00000000000000000000000000000000>:0) UnityEngine.EventSystems.ExecuteEvents.Execute[T] (UnityEngine.GameObject target, UnityEngine.EventSystems.BaseEventData eventData, UnityEngine.EventSystems.ExecuteEvents+EventFunction1[T1] functor) (at <00000000000000000000000000000000>:0)
UnityEngine.EventSystems.StandaloneInputModule.ReleaseMouse (UnityEngine.EventSystems.PointerEventData pointerEvent, UnityEngine.GameObject currentOverGo) (at <00000000000000000000000000000000>:0)
UnityEngine.EventSystems.StandaloneInputModule.ProcessMousePress (UnityEngine.EventSystems.PointerInputModule+MouseButtonEventData data) (at <00000000000000000000000000000000>:0)
UnityEngine.EventSystems.StandaloneInputModule.ProcessMouseEvent (System.Int32 id) (at <00000000000000000000000000000000>:0)
UnityEngine.EventSystems.StandaloneInputModule.Process () (at <00000000000000000000000000000000>:0)
UnityEngine.EventSystems.EventSystem.Update () (at <00000000000000000000000000000000>:0)
--- End of stack trace from previous location where exception was thrown ---
WalletConnectUnity.Demo.SimpleSign.ConnectScreen.OnConnect () (at <00000000000000000000000000000000>:0)
System.Runtime.CompilerServices.AsyncVoidMethodBuilder.Start[TStateMachine] (TStateMachine& stateMachine) (at <00000000000000000000000000000000>:0)
WalletConnectUnity.Demo.SimpleSign.ConnectScreen.OnConnect () (at <00000000000000000000000000000000>:0)
UnityEngine.Events.InvokableCall.Invoke (System.Object[] args) (at <00000000000000000000000000000000>:0)
UnityEngine.Events.UnityEvent.Invoke () (at <00000000000000000000000000000000>:0)
UnityEngine.EventSystems.ExecuteEvents.Execute[T] (UnityEngine.GameObject target, UnityEngine.EventSystems.BaseEventData eventData, UnityEngine.EventSystems.ExecuteEvents+EventFunction`1[T1] functor) (at <00000000000000000000000000000000>:0)
UnityEngine.EventSystems.StandaloneInputModule.ReleaseMouse (UnityEngine.EventSystems.PointerEventData pointerEvent, UnityEngine.GameObject currentOverGo) (at <00000000000000000000000000000000>:0)
UnityEngine.EventSystems.StandaloneInputModule.ProcessMousePress (UnityEngine.EventSystems.PointerInputModule+MouseButtonEventData data) (at <00000000000000000000000000000000>:0)
UnityEngine.EventSystems.StandaloneInputModule.ProcessMouseEvent (System.Int32 id) (at <00000000000000000000000000000000>:0)
UnityEngine.EventSystems.StandaloneInputModule.Process () (at <00000000000000000000000000000000>:0)
UnityEngine.EventSystems.EventSystem.Update () (at <00000000000000000000000000000000>:0)
--- End of stack trace from previous location where exception was thrown ---
System.Runtime.CompilerServices.AsyncMethodBuilderCore+<>c.b__7_0 (System.Object state) (at <00000000000000000000000000000000>:0)
UnityEngine.UnitySynchronizationContext+WorkRequest.Invoke () (at <00000000000000000000000000000000>:0)
UnityEngine.UnitySynchronizationContext.Exec () (at <00000000000000000000000000000000>:0)

Requesting a solution for this.

Thanks

**Comment by GaoG001108** [comment]
Didn't you report the error 'socket stalled'? The error you displayed should have been caused by not connecting the socket to the package. I also encountered the same problem

**Comment by yozdev** [comment]
Hey @GaoG001108 

I didn't get socket stalled error. Everything is running smoothly in editor.

This error is showing up when I run a Windows Desktop build for the demo scene.

**Comment by yozdev** [comment]
It's fixed it latest update. Thank you team.
