### ISSUE TITLE
eth_sign: HOW TO?

### ISSUE THREAD

**Issue by dpradell-dev** [WalletConnect/WalletConnectUnity#86]

**Comment by dpradell-dev** [comment]
Can't find anywhere how to perform the simplest of the transactions, an `eth_sign`. Could somebody please just complete [this](https://github.com/WalletConnect/WalletConnectUnity/blob/ae8dced3894950dec69c8c64f7560b895b97f98e/Assets/WalletConnectUnity/Demo/SimpleSign/Scripts/AuthScreen.cs#L29) and show the rest how to do it? Let's say the documentation doesn't help with figuring it out :)

@gigajuwels

Thanks.

**Comment by dpradell-dev** [comment]
This is how my request class looks:

```
[RpcMethod("eth_sign")]
  public class EthSignRequest
  {
      [JsonProperty("id")]
      public int id { get; set; }
      [JsonProperty("jsonrpc")]
      public string jsonrpc { get; set; }
      [JsonProperty("method")]
      public string method { get; set; }
      [JsonProperty("params")]
      public string[] parameters { get; set; }
      
      public EthSignRequest(int id, string jsonrpc, string method, params string[] parameters)
      {
          this.id = id;
          this.jsonrpc = jsonrpc;
          this.method = method;
          this.parameters = parameters;
      }
  }
```

And this is how I create the request:

```
EthSignRequest request = new EthSignRequest(1, "jsonrpc", "eth_sign", new[] {address, message});
                
                string topic = _connectedData.Approval.Result.Topic;
                // Call the Request function and handle the Task<TR> result using async/await or ContinueWith or any other approach.
                Task<EthSignResult> requestTask = wcSignClient.Request<EthSignRequest, EthSignResult>(topic, request, chainId);
                await requestTask.ContinueWith(HandleRequestResult);
```

Finally this is the error I'm getting:
![image](https://github.com/WalletConnect/WalletConnectUnity/assets/99496843/ac937f7e-aa29-4673-adc7-1544d5d4e4f0)

Can someone identify what I'm doing wrong?

Thanks in advance!

**Comment by dpradell-dev** [comment]
@gigajuwels any insights on this? thanks!

**Comment by nikitaessen** [comment]
![image](https://github.com/WalletConnect/WalletConnectUnity/assets/19946297/aacbf0f3-2bbd-486b-a47f-629ea0e4576b)
![image](https://github.com/WalletConnect/WalletConnectUnity/assets/19946297/33c8c2b8-9674-475c-aa8c-e20345cb11c5)

this worked for me

@dpradell-dev

**Comment by dpradell-dev** [comment]
Thank your for taking the time @nikitaessen! Tried exactly as you did but still getting the "invalid parameters" error. What version of WalletConnectUnity are you using? Thanks again!

**Comment by dpradell-dev** [comment]
Ok for everyone with this issue, @nikitaessen response is CORRECT but here's an important aclaration:

`chainId` needs to be passed as "ChainNamespace:ChainId", something like: **`"eip155:80001"`**
