### ISSUE TITLE
TimeoutException: socket stalled

### ISSUE THREAD

**Issue by GaoG001108** [WalletConnect/WalletConnectUnity#87]
I am very happy that you have updated the Unity library. The previous signature issues I encountered when using the new code have been resolved, but after packaging, I still report TimeoutException: socket blocked. I use Mac packaging to run, but it runs well when I am not packaging. Have you conducted packaging testing and encountered the same problem. I am very willing to continue following updates to the library and hope that this issue can be resolved. @michitomo @KoenRijpstra @ecp4224 @chris13524

**Comment by yozdev** [comment]
I'm getting the same error on Windows Desktop build

**Comment by agelessZeal** [comment]
I have got the same issue on android build

**Comment by agelessZeal** [comment]
only testing on unity platform is working well.

**Comment by gigajuwels** [comment]
hi @agelessZeal @yozdev @GaoG001108 this issue should be fixed by now, as the simple dapp demo is fully working and tested on android mobile. Can you confirm this issue is resolved? If not, can you provide some details on how you reproduce this and what error you are getting?
Thank you

**Comment by yozdev** [comment]
Hi @gigajuwels I've tested using Windows build and Android build. Both are working perfectly for me.

Thank you for resolving the issue.
