### ISSUE TITLE
Error on fresh installation

### ISSUE THREAD

**Issue by grandwiz** [WalletConnect/WalletConnectUnity#89]
I get this error on a fresh installation, any suggestions?
`Assets\WalletConnectUnity\Scripts\WalletConnectUnity\WCWebSocketBuilder.cs(7,54): error CS0738: 'WCWebSocketBuilder' does not implement interface member 'IConnectionBuilder.CreateConnection(string)'. 'WCWebSocketBuilder.CreateConnection(string)' cannot implement 'IConnectionBuilder.CreateConnection(string)' because it does not have the matching return type of 'IJsonRpcConnection'.`

**Comment by gigajuwels** [comment]
hi @grandwiz this issue should be fixed now, as the simple dapp demo is fully working and tested on desktop and mobile. Can you confirm this issue is resolved? If not, can you try using the latest commit in this repo and try again?

**Comment by gigajuwels** [comment]
closing now, reopen if you are experiencing this issue
