### ISSUE TITLE
Hi, It is not working on Desktop build

### ISSUE THREAD

**Issue by SuperCoder-Net** [WalletConnect/WalletConnectUnity#9]
Hi, I am going to connect wallet to my unity game using this repo.
It is working on Unity Edtor, but it is not working on Desktop build.
Why?
 could you give me any help?
email: savaspasic8@gmail.com
discord: mRcoin#4355
telegram: @mRcoin1220

please let me know asap.
Best

**Comment by gigajuwels** [comment]
@SuperCoder-Net Please provide steps to reproduce in the [discussions](https://github.com/WalletConnect/WalletConnectUnity/discussions) section of this repo. You can also ask questions and engage with other developers there
