### ISSUE TITLE
Core.Start() is not executed correctly

### ISSUE THREAD

**Issue by agelessZeal** [WalletConnect/WalletConnectUnity#90]
I have run the v2 of the walletConnectUnity for android.  When I build the simple demo and click connect button, nothing happens.
The issue is WalletConnectSignClient object is null.
The WalletConnectSignClient.init function is not called.

I have debugged all. The issue comes from  this code : 
    await WalletConnectUnity.InitCore();  /// WCSignClient.cs

 above code is not called at all. 
because 
  await Core.Start();  /// WalletConnectUnity.cs InitCore function 
This code is not executed.
Is there any demo complete apk?

**Comment by agelessZeal** [comment]
Is there any  successful apk with wallet connect v2?

**Comment by dpradell-dev** [comment]
I subscribe to this issue, same is happening to me.

**Comment by gigajuwels** [comment]
Hi @agelessZeal and @dpradell-dev, this issue should be fixed now, as the simple dapp demo is fully working on desktop and mobile. Can you confirm this issue is resolved? If not, can you provide some details on how you reproduce this and what error you are getting?
Thank you

**Comment by gigajuwels** [comment]
closing for now, reopen if youre still experiencing this issue.
