### ISSUE TITLE
SignClient.Connect() getting stuck

### ISSUE THREAD

**Issue by dpradell-dev** [WalletConnect/WalletConnectUnity#91]
As said in title, SignClient.Connect() gets stuck here, getting no `connectData`, without throwing errors:
![image](https://github.com/WalletConnect/WalletConnectUnity/assets/99496843/948a3e95-5980-4f52-820d-15dfd9640399)

Same behaviour/issue anybody?

Thanks in advance!

**Comment by gigajuwels** [comment]
closing for now, reopen if you are still experiencing this issue.
